Tailormap/tailormap-viewer

- projects/core/src/lib/components/feature-info/feature-info.service.ts
Both the backend as well as the API spec have a value of 4, not 10:
https://github.com/B3Partners/tailormap-api/blob/46972f3fc7ff85d158f0e0e361bb30f0fd110573/src/main/java/nl/b3p/tailormap/api/controller/FeaturesController.java#L157
https://github.com/B3Partners/tailormap-api/blob/46972f3fc7ff85d158f0e0e361bb30f0fd110573/src/main/resources/tailormap-api.yaml#L509-L515
resolves HTM-332
> [HTM-332] synchronize the featureinfo buffer distance with the default value from the API

- docker-compose.yml
- docker/web/nginx.conf
Expose the nginx stub_status to a converter that then provides prometheus metrics. Will provide something like below:
```
mark @ mark-desktop /tmp
└─ $ ▶ curl http://localhost:9113/metrics
nginx_connections_accepted 37
nginx_connections_active 3
nginx_connections_handled 37
nginx_connections_reading 0
nginx_connections_waiting 2
nginx_connections_writing 1
nginx_http_requests_total 50
nginx_up 1
nginxexporter_build_info{commit="7a03d0314425793cf4001f0d9b0b2cfd19563433",date="2021-12-21T19:24:34Z",version="0.10.0"} 1
```
> [HTM-336] Expose the nginx stub_status

- .github/workflows/test-and-deploy.yml
- Dockerfile
see https://github.com/nodejs/node/blob/main/doc/changelogs/CHANGELOG_V16.md#16.17.0
resolves HTM-445
> [HTM-445] Bump NodeJS from 16.16.0 to 16.17.0

- Dockerfile
- angular.json
- locale/messages.en-US.xlf
- locale/messages.nl.xlf
- package.json
- projects/api/src/typings.d.ts
- projects/app/src/typings.d.ts
- projects/core/src/lib/components/drawing/drawing-menu-button/drawing-menu-button.component.ts
- projects/core/src/lib/components/drawing/drawing-style-form/drawing-style-form.component.html
- projects/core/src/lib/components/drawing/helpers/drawing.helper.ts
- projects/core/src/lib/components/feature-info/feature-info.service.ts
- projects/core/src/lib/components/feature-info/feature-info/feature-info.component.ts
- projects/core/src/lib/components/menubar/profile/profile.component.html
- projects/core/src/lib/components/menubar/profile/profile.component.ts
- projects/core/src/lib/components/print/print-menu-button/print-menu-button.component.ts
- projects/core/src/lib/components/toc/toc-menu-button/toc-menu-button.component.ts
- projects/core/src/lib/components/toolbar/clicked-coordinates/clicked-coordinates.component.ts
- projects/core/src/lib/map/state/map.effects.ts
- projects/core/src/lib/services/load-application.service.ts
- projects/core/src/lib/services/map-pdf/map-pdf.service.ts
- projects/core/src/typings.d.ts
- projects/map/src/lib/openlayers-map/openlayers-map-image-exporter.ts
- projects/map/src/typings.d.ts
- projects/shared/src/typings.d.ts
Contains initial translation to Dutch.
To run the viewer in Dutch use `npm run start-nl` to get a localized version of the app.
Run `npm run build-localized` to build the application for both English and Dutch (will be added in `dist/en-US` and `dist/nl`.
> Translations setup

- projects/core/src/lib/components/toolbar/mouse-coordinates/mouse-coordinates.component.css
- projects/core/src/lib/components/toolbar/mouse-coordinates/mouse-coordinates.component.html
- projects/core/src/lib/components/toolbar/mouse-coordinates/mouse-coordinates.component.ts
This stops the coordinates from jittering when moving the mouse around, and the size of the box being a guess.
<details>
<summary>Before and after</summary>
</details>
> Adjust mouse coordinate sizes, use tabular numbers

- projects/core/src/lib/components/feature-info/feature-info-dialog/feature-info-dialog.component.html
- projects/core/src/lib/components/feature-info/feature-info-dialog/feature-info-dialog.component.spec.ts
- projects/core/src/lib/components/feature-info/feature-info-dialog/feature-info-dialog.component.ts
- projects/core/src/lib/components/feature-info/helpers/feature-info.helper.ts
- projects/core/src/lib/components/feature-info/models/feature-info.model.ts
- projects/core/src/lib/components/feature-info/state/feature-info.selectors.ts
- projects/core/src/lib/map/state/map.selectors.ts
- projects/shared/src/lib/helpers/array.helper.spec.ts
- projects/shared/src/lib/helpers/array.helper.ts
instead of alphabetically sorting the the attributes by name...
The collection of configured attributes is sorted according to the `list_index`, see:
https://github.com/B3Partners/tailormap-persistence/blob/e1dd76a7ca0b0a1a7d280adf0f2eda1ab5e66720/src/main/java/nl/tailormap/viewer/config/app/ApplicationLayer.java#L89-L90
before:
after:
resolves HTM-451, HTM-452
> [HTM-451][HTM-452] use as-is sorting for the feature info rendering

- projects/shared/src/lib/helpers/url.helper.ts
Fixes
```
Error: projects/shared/src/lib/helpers/url.helper.ts:20:41 - error TS2339: Property 'entries' does not exist on type 'URLSearchParams'.
```
> Use URLSearchParams forEach() instead of entries()

- .github/workflows/test-and-deploy.yml
to prevent errors thet say:
```
WARNING: Some service image(s) must be built from source by running:
docker compose build %s db web-proxied
error during connect: Post "http://docker.example.com/v1.41/images/create?fromImage=nginx%2Fnginx-prometheus-exporter&tag=0.10.0": command [ssh -l github-docker-actions -- *** docker system dial-stdio] has exited with signal: killed, please make sure the URL is valid, and Docker 18.09 or later is installed on the remote host: stderr=
```
> Revert to old docker-compose for pulling snapshot images on main branch deployment

- projects/map/src/lib/helpers/ol-layer.helper.ts
If the server does not understand the DPI parameter it will render images with thinner lines and smaller fonts, so do not assume it by default.
> [HTM-488] Do not assume geoserver hidpi serverType for generic services

- .github/workflows/test-and-deploy.yml
- Dockerfile
- bin/prebuild.js
- docker-compose-pr.yml
- docker-compose.yml
- docker/web/configure-sentry.sh
- package-lock.json
- package.json
- projects/app/src/index.html
- projects/app/src/main.ts
- projects/core/src/lib/core.module.ts
- tsconfig.json
This adds two secrets to the GitHub Actions: `VIEWER_SENTRY_DSN` and `API_SENTRY_DSN`.
Sentry DSN is injected into `index.html` to be able to include errors that happen while initializing Angular (e.g. `tailormap-api` unavailable).
resolves HTM-322, HTM-466
> [HTM-322, HTM-466] Enable sentry

- .github/workflows/test-and-deploy.yml
- Dockerfile
- README.md
- docker-compose.yml
This brings us `linux/amd` and `linux/arm64` docker images
resolves [HTM-516]
[HTM-525]: https://b3partners.atlassian.net/browse/HTM-525?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[HTM-516]: https://b3partners.atlassian.net/browse/HTM-516?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[HTM-526]: https://b3partners.atlassian.net/browse/HTM-526?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[HTM-524]: https://b3partners.atlassian.net/browse/HTM-524?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [HTM-516] Build platform independent images

- package-lock.json
see also https://github.com/advisories/GHSA-76p3-8jx3-jpfq
> Bump loader-utils from 2.0.2 to 2.0.3 to resolve CVE-2022-37601

- .github/workflows/test-and-deploy.yml
- Dockerfile
- README.md
- package-lock.json
- package.json
18.x is the current LTS version and the viewer-admin is already using that: https://github.com/B3Partners/tailormap-admin/blob/aba65eace4612210cbf5888d743a48101feb55e0/pom.xml#L122-L123
resolves HTM-564
> Bump NodeJS from 16.x to 18.x

- projects/app/src/main.ts
Due to how the bookmarks are generated, any time the user moves the map or zooms in/out is considered a new "session" to Sentry. As we don't use it for usage tracking, disable session tracking and only depend on the random 1% error tracking.
> app: disable Sentry session tracking

- README.md
- docker-compose.yml
Secure by default even when running in host network mode. Requires https://github.com/B3Partners/tailormap-api/pull/336
> Change default listen address from localhost to 0.0.0.0 in Compose

- projects/core/src/lib/components/toolbar/simple-search/simple-search.component.spec.ts
- projects/core/src/lib/components/toolbar/simple-search/simple-search.component.ts
- projects/map/src/lib/helpers/feature.helper.spec.ts
- projects/map/src/lib/helpers/feature.helper.ts
> [HTM-538] F - Location search in ESPG:3857 viewer zooms to EPSG:4326 coordinates

- projects/admin-core/src/lib/useradmin/groupdetails-form/groupdetails-form.component.html
- projects/admin-core/src/lib/useradmin/groupdetails-form/groupdetails-form.component.spec.ts
- projects/admin-core/src/lib/useradmin/groupdetails-form/groupdetails-form.component.ts
- projects/admin-core/src/lib/useradmin/userdetails-form/userdetails-form.component.html
- projects/admin-core/src/lib/useradmin/userdetails-form/userdetails-form.component.spec.ts
- projects/admin-core/src/lib/useradmin/userdetails-form/userdetails-form.component.ts
also disallow strange (non-alfa-numeric) characters, only `[a-zA-Z0-9]*` are allowed, the Add/Save button is disabled when the form data is invalid.
resolves HTM-727
> [HTM-727] Disallow blank username and group name

- projects/app/src/index.html
So we don't have to specify this manually for every link. Useful for links in attributions, feature info, etc.
I don't think it will interfere in the normal functionality in our single-page app.
> Set "_blank" as default target for links

- projects/api/src/lib/services/tailormap-api-v1.service.model.ts
- projects/api/src/lib/services/tailormap-api-v1.service.ts
the option defaults to false to preserve existing behaviour
see also https://github.com/B3Partners/tailormap-api/pull/514
> [HTM-860] Add a `geometryInAttributes` option for the `/features` endpoint

- projects/admin-api/src/lib/services/tailormap-admin-api-v1-mock.service.ts
- projects/admin-api/src/lib/services/tailormap-admin-api-v1-service.model.ts
- projects/admin-api/src/lib/services/tailormap-admin-api-v1.service.ts
- projects/admin-core/src/lib/catalog/feature-source-form-dialog/feature-source-form-dialog.component.ts
- projects/admin-core/src/lib/catalog/geo-service-form-dialog/geo-service-form-dialog.component.ts
- projects/admin-core/src/lib/catalog/geo-service-layer-form-dialog/geo-service-layer-form-dialog.component.ts
- projects/admin-core/src/lib/catalog/helpers/geo-service.helper.ts
- projects/admin-core/src/lib/catalog/services/geo-service.service.ts
- projects/admin-core/src/lib/shared/services/admin-snackbar.service.ts
Requires https://github.com/B3Partners/tailormap-api/pull/516
When creating or refreshing a geo service with an invalid URI like:
- `not a url`
- `ftp://google.com/`
- `https://offline.invalid`
- `https://google.com:1337`
- `https://google.com/`
An error message will be shown in the snackbar.
Some errors are only returned when refreshing capabilities, but you can't save an invalid URL so there is an error message shown for the first one when saving an existing service with that URL value.
> [HTM-849] Display friendly error messages when creating service

- .github/workflows/cleanup-and-maintainance.yml
As it appears to be impossible to detect multi-arch untagged images
ref: https://support.github.com/ticket/personal/0/2288180
> [HTM-683] Disable cleanup of untagged docker images

- projects/api/src/lib/mock-data/tailormap-api.mock-data.ts
- projects/api/src/lib/models/coordinate-reference-system.model.ts
- projects/map/src/lib/helpers/projections.helper.ts
- projects/map/src/lib/openlayers-map/openlayers-map.ts
The OpenLayers projection was initialized with the extent set to the max extent the admin configured for the app. This is obviously wrong, but even if the app max extent was set to the EPSG:3857 extent in the admin (or the code would use the projection extent from `/api/app/.../map` member `crs.bounds`), there would be a mismatch for the latitude range (official [EPSG:3857](https://epsg.io/3857) goes from [-85.06, 85.06] but the projection extent for OL should be [-90.0, 90.0].  As a fix just use the string as projection instead of creating a new OL Projection. OL recognizes the 'EPSG:3857' string and uses the correct extent. For other projections such as EPSG:28992 this change does not seem to matter.
Also actually applies the max map view extent.
TODO:
> [HTM-932] Fix map shift for web mercator projection

- docker-compose.yml
I've tested it works by adding it to `.env` and printing `Session.getMaxInactiveInterval()`.
> HTM-963: Pass through environment variable to set session timeout

- projects/admin-core/assets/locale/messages.admin-core.en.xlf
- projects/admin-core/assets/locale/messages.admin-core.nl.xlf
- projects/admin-core/src/lib/catalog/catalog-create-buttons/catalog-create-buttons.component.html
- projects/admin-core/src/lib/catalog/catalog-create-buttons/catalog-create-buttons.component.spec.ts
- projects/admin-core/src/lib/catalog/feature-source-form/feature-source-form.component.ts
Empty title is allowed for map services as well. By allowing empty title for WFS the title of the WFS itself will be shown in the catalog (after fix that user entered title was overwritten by WFS title).
> Small catalog updates: allow empty feature source title, add map service label

- .github/workflows/test-and-deploy.yml
- ci/docker-compose.pr.yml
...instead of setting `image` for the `db` service to `rwgrim/docker-noop` which is too old for current Docker version:
```
[DEPRECATION NOTICE] Docker Image Format v1 and Docker Image manifest version 2, schema 1 support is disabled by default and will be removed in an upcoming release. Suggest the author of docker.io/rwgrim/docker-noop:latest to upgrade the image to the OCI Format or Docker Image manifest v2, schema 2.
```
This however requires a newer Compose plugin version than v2.23.3 installed in the [GitHub runner image](https://github.com/actions/runner-images/blob/ubuntu22/20240414.1/images/ubuntu/Ubuntu2204-Readme.md)
> Fix PR deployment: remove db container using YAML !reset tag

- projects/core/src/lib/components/edit/edit-dialog/edit-dialog.component.css
- projects/core/src/lib/components/feature-info/feature-info-dialog/feature-info-dialog.component.css
use
```css
word-break: normal;
overflow-wrap: break-word;
```
instead of `word-break: break-all;`
resolves HTM-1114
> [HTM-1114] Feature-info text not broken properly when text in attribute is long

- projects/map/src/lib/openlayers-map/open-layers-layer-manager.ts
- projects/shared/src/lib/components/legend-image/legend-image.component.ts
Requires serverType to be set to 'mapserver' (autodetect by 'mapserv' in URL, not overrideable in admin for now).
> Support high DPI legends for MapServer

- ci/tailormap-embed-test/compose.yaml
> HTM-1131: Traefik Host rule does not support multiple hostnames anymore

- .github/workflows/test-and-deploy.yml
ideally we should get rid of this variable and use the default, see also https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2204-Readme.md (currently at 2.27.1 which has a known problem)
> [CI] update COMPOSE_VERSION to 2.27.2

- .github/workflows/test-and-deploy.yml
- docker-compose.yml
When we have a solr service running we also want to be able to monitor the solr service
> Consolidate the 2 Solr profiles into one

- .github/workflows/codeql-analysis.yml
- .github/workflows/test-and-deploy.yml
- .github/workflows/trivy.yml
stop the workflow when there is another push to the branch (unless it is the main branch)
> [CI] Prevent concurrent workflow runs on the same branch

- .github/workflows/test-and-deploy.yml
- Dockerfile
Update NodeJS to 20.15.0 in workflow and base image to 20.15.0 in Dockerfile
> Update NodeJS to 20.15.0

- projects/admin-core/src/lib/catalog/feature-type-selector/feature-type-selector.component.ts
- projects/admin-core/src/lib/search-index/search-index-form/search-index-form.component.html
- projects/admin-core/src/lib/search-index/search-index-form/search-index-form.component.ts
[![HTM-1205](https://badgen.net/badge/JIRA/HTM-1205/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1205) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
HTM-1205 F: Solr indexing supports WFS, this should be disabled (admin)
* Added input option in FeatureTypeSelectorComponent to allow passing in feature source protocols that should be excluded.
* Used input option in search-index-form.component.html to exclude WFS
[HTM-1205]: https://b3partners.atlassian.net/browse/HTM-1205?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> HTM-1205: Prevent creating Solr indexes for WFS feature types

- projects/shared/src/lib/helpers/file.helper.ts
[![HTM-1230](https://badgen.net/badge/JIRA/HTM-1230/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1230) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
[HTM-1230]: https://b3partners.atlassian.net/browse/HTM-1230?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> HTM-1230: Fix error exporting layer when WFS does not return a (valid) Content-Disposition header

- projects/core/src/lib/map/services/application-map.service.ts
- projects/shared/src/lib/helpers/htmlify.helper.spec.ts
- projects/shared/src/lib/helpers/htmlify.helper.ts
- projects/shared/src/lib/helpers/index.ts
- projects/shared/src/lib/pipes/htmlify.constants.ts
- projects/shared/src/lib/pipes/htmlify.pipe.ts
[![HTM-816](https://badgen.net/badge/JIRA/HTM-816/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-816) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
[HTM-816]: https://b3partners.atlassian.net/browse/HTM-816?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
This is a somewhat breaking change. If previously HTML was used in attributions this will now render as plain text so attributions might need be converted to non-HTML with (optional) Markdown style links
> HTM-816: Escape HTML in layer attributions

- projects/core/src/lib/components/feature-info/feature-info-dialog/feature-info-dialog.component.css
- projects/core/src/lib/components/feature-info/feature-info-layer-item/feature-info-layer-item.component.css
[![HTM-1261](https://badgen.net/badge/JIRA/HTM-1261/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1261) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
* Added maximum width for feature-info layer-list-wrapper 
* Make layer title in feature-info-layer-item wrap so the entire title is displayed
[HTM-1261]: https://b3partners.atlassian.net/browse/HTM-1261?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> HTM-1261: Maximum width for feature-info layer-list

- projects/core/src/lib/components/toc/toc-node-layer/toc-node-layer.component.css
- projects/core/src/lib/components/toc/toc-node-layer/toc-node-layer.component.html
- projects/core/src/lib/components/toc/toc/toc.component.css
[![HTM-1264](https://badgen.net/badge/JIRA/HTM-1264/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1264) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
* Set height of tree-node in toc-tree to fit-content.
* Made text in .tree-node__label-content wrap.
[HTM-1264]: https://b3partners.atlassian.net/browse/HTM-1264?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> HTM-1264: Make long layer titles visible in TOC

- projects/core/src/lib/components/toc/toc-node-layer/toc-node-layer.component.css
[![HTM-1264](https://badgen.net/badge/JIRA/HTM-1264/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1264) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
long layer titles are broken up between words, but if the word is too long it breaks anywhere.
[HTM-1264]: https://b3partners.atlassian.net/browse/HTM-1264?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> HTM-1264: long layer titles are broken over multiple lines

- docker-compose.yml
[![HTM-1319](https://badgen.net/badge/JIRA/HTM-1319/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1319) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
Use the new docker images that comes with JTS ready to use.
**⛓️‍💥 Note: when upgrading you will need to fully redeploy the Solr service (including dropping any associated volumes) so full-text indexes can be recreated with the correct geometry type** 
requires https://github.com/Tailormap/tailormap-data/pull/13
related to https://github.com/Tailormap/tailormap-api/pull/1025
[HTM-1319]: …
> ⛓️‍💥 HTM-1319: Replace Solr image in the Tailormap stack with the new image⛓️‍💥

- projects/shared/src/lib/helpers/htmlify.helper.ts
- projects/shared/src/lib/helpers/markdown.helper.spec.ts
- projects/shared/src/lib/helpers/markdown.helper.ts
[![HTM-1334](https://badgen.net/badge/JIRA/HTM-1334/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1334) [![HTM-1335](https://badgen.net/badge/JIRA/HTM-1335/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1335)[<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
HTM-1334: Escape spaces in markdown-link urls
HTM-1335: Fix markdown escaping other values than strings
[HTM-1334]: https://b3partners.atlassian.net/browse/HTM-1334?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[HTM-1335]: …
> HTM-1334 | HTM-1335: Markdown fixes

- projects/admin-api/src/lib/models/search-index-summary.model.ts
- projects/admin-api/src/lib/models/search-index.model.ts
- projects/admin-core/assets/locale/messages.admin-core.de.xlf
- projects/admin-core/assets/locale/messages.admin-core.en.xlf
- projects/admin-core/assets/locale/messages.admin-core.nl.xlf
- projects/admin-core/src/lib/search-index/search-index-create/search-index-create.component.ts
- projects/admin-core/src/lib/search-index/search-index-edit/search-index-edit.component.ts
- projects/admin-core/src/lib/search-index/search-index-form/search-index-form.component.html
- projects/admin-core/src/lib/search-index/search-index-form/search-index-form.component.ts
- projects/admin-core/src/lib/search-index/state/search-index.actions.ts
[![HTM-1368](https://badgen.net/badge/JIRA/HTM-1368/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1368) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
removes the `comment` field and add the `summary` to the models (using the summary information is for a different PR)
must be merged with https://github.com/Tailormap/tailormap-api/pull/1082
[HTM-1368]: https://b3partners.atlassian.net/browse/HTM-1368?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> HTM-1368: Update SearchIndexModel and usage for API change

- projects/admin-core/src/lib/search-index/search-index-form/search-index-form.component.ts
- projects/admin-core/src/lib/shared/services/admin-sse.service.ts
[![HTM-1402](https://badgen.net/badge/JIRA/HTM-1402/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1402)
[![HTM-1402](https://badgen.net/badge/JIRA/HTM-1404/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1404) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
companion to https://github.com/Tailormap/tailormap-api/pull/1105, part of https://b3partners.atlassian.net/browse/HTM-1401
[HTM-1402]: https://b3partners.atlassian.net/browse/HTM-1402?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> HTM-1401 | HTM-1402 | HTM-1404: Update task-progress event to have optional map of task data and use that to show indexing progress

- projects/core/src/lib/components/toolbar/simple-search/simple-search.service.ts
[![HTM-1371](https://badgen.net/badge/JIRA/HTM-1371/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1371) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
add parenthesis to preserve whitespace in the `searchTerm`; this should fix the problem, as demonstrated here: https://github.com/Tailormap/tailormap-api/blob/b3c9b38d9a1c1038a659ee43e3d3948c33ff4ecc/src/test/java/org/tailormap/api/controller/SearchControllerIntegrationTest.java#L223-L239
[HTM-1371]: https://b3partners.atlassian.net/browse/HTM-1371?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0 …
> HTM-1371: Can't search for values with spaces in them with Solr

- projects/core/src/lib/components/legend/legend/legend.component.spec.ts
- projects/core/src/lib/components/legend/services/legend.service.ts
- projects/core/src/lib/map/services/application-map.service.ts
- projects/core/src/lib/test-helpers/map-service.mock.spec.ts
- projects/map/src/lib/helpers/ol-layer.helper.ts
- projects/map/src/lib/map-service/map.service.ts
- projects/map/src/lib/models/wms-layer.model.ts
[![HTM-1060](https://badgen.net/badge/JIRA/HTM-1060/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1060) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
This adds eg `LANGUAGE=nl` to GeoServer `getMap` and `getlegendGraphic` requests
see also https://github.com/Tailormap/tailormap-data/pull/25 for the data 
[HTM-1060]: https://b3partners.atlassian.net/browse/HTM-1060?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> HTM-1060: Support i18n in map service requests

- docker-compose.yml
[![HTM-1422](https://badgen.net/badge/JIRA/HTM-1422/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1422) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
changelist: https://solr.apache.org/docs/9_8_0/changes/Changes.html
As [noted](https://solr.apache.org/guide/solr/latest/upgrade-notes/major-changes-in-solr-9.html#configuration) a warning may be logged for `numVersionBuckets`. I don't thing any of the other changes affect our custom image.
see https://github.com/Tailormap/tailormap-data/pull/26
[HTM-1422]: https://b3partners.atlassian.net/browse/HTM-1422?atlOrigin=eyJpIj …
> HTM-1422: Upgrade Solr from 9.7.0 to 9.8.0

- projects/shared/src/lib/components/split-button/split-button.component.html
[![SUPPORT-14902](https://badgen.net/badge/JIRA/SUPPORT-14902/pink?icon=jira)](https://b3partners.atlassian.net/browse/SUPPORT-14902) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
resolves https://b3partners.atlassian.net/browse/SUPPORT-14902
> SUPPORT-14902 | HTM-1424 : Change the tooltip position of the background layer dropdown options to "before" (from default "below")

- projects/admin-core/assets/locale/messages.admin-core.de.xlf
- projects/admin-core/assets/locale/messages.admin-core.en.xlf
- projects/admin-core/assets/locale/messages.admin-core.nl.xlf
- projects/admin-core/src/lib/catalog/feature-type-form/feature-type-form.component.html
[![HTM-1430](https://badgen.net/badge/JIRA/HTM-1430/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1430) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
[HTM-1430]: https://b3partners.atlassian.net/browse/HTM-1430?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> HTM-1430: Add warning messages when a feature type does not have a primary key and/or geometry attribute

- projects/admin-core/assets/locale/messages.admin-core.de.xlf
- projects/admin-core/assets/locale/messages.admin-core.en.xlf
- projects/admin-core/assets/locale/messages.admin-core.nl.xlf
- projects/admin-core/src/lib/catalog/feature-type-attributes/feature-type-attributes.component.html
- projects/admin-core/src/lib/catalog/feature-type-attributes/feature-type-attributes.component.ts
- projects/admin-core/src/lib/catalog/feature-type-form/feature-type-form.component.html
[![HTM-1443](https://badgen.net/badge/JIRA/HTM-1443/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1443) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
[HTM-1443]: https://b3partners.atlassian.net/browse/HTM-1443?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> HTM-1443: show key icon next to primary key attribute

- .github/dependabot.yml
- docker-compose.yml
[![EK-15](https://badgen.net/badge/JIRA/EK-15/pink?icon=jira)](https://b3partners.atlassian.net/browse/EK-15) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
To support storing drawings.
**THIS IS A BREAKING CHANGE; it requires a full dump and restore of the Tailormap database** as this is a major database version bump. The procedure is described in detail in the README: [Backing up the configuration database](https://github.com/Tailormap/tailormap-viewer?tab=readme-ov-file#backing-up-the-configuration-database), [Restoring a …
> ⛓️‍💥 EK-15: replace the PostgreSQL 15 image with a PostGIS 17-3.5 image ⛓️‍💥

- projects/core/src/lib/map/state/map.selectors.ts
[![HTM-1440](https://badgen.net/badge/JIRA/HTM-1440/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1440) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
Because the geometry attribute name is required to create CQL filters.
[HTM-1440]: https://b3partners.atlassian.net/browse/HTM-1440?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fixes HTM-1440: only show filterable layers with attributes

- projects/admin-core/src/lib/catalog/catalog-base-tree/catalog-base-tree-node/catalog-base-tree-node.component.ts
[![HTM-1453](https://badgen.net/badge/JIRA/HTM-1453/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1453) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
Note: the primary key warning is still shown for WFS feature types in the `FeatureTypeFormComponent`, but as you need the feature source protocol this is easier to change in #820 : 51ef50a2f6adca6f88bca8914266acfbf55de309
[HTM-1453]: https://b3partners.atlassian.net/browse/HTM-1453?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> HTM-1453, HTM-1454: Fix catalog node warnings

- projects/map/src/lib/openlayers-map/helpers/open-layers-wms-get-feature-info.helper.ts
[![HTM-1189](https://badgen.net/badge/JIRA/HTM-1189/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1189) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
A maximum of 10 features per layer is an arbitrary choice; in the past this is a number that proved to perform well
[HTM-1189]: https://b3partners.atlassian.net/browse/HTM-1189?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> HTM-1189: increase the WMS getFeatureInfo maximum features count from 1 (default) to 10

- .eslintrc.json
- package-lock.json
- package.json
[![HTM-1467](https://badgen.net/badge/JIRA/HTM-1467/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1467) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
Update `angular-eslint/*` `devDependencies` to 19 and disable prefer-standalone lint rule
[HTM-1467]: https://b3partners.atlassian.net/browse/HTM-1467?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> HTM-1467: update angular-eslint devDependencies to 19 and disable prefer-standalone lint rule

- projects/map/src/lib/map-service/map.service.ts
- projects/map/src/lib/openlayers-map/open-layers-event-manager.spec.ts
- projects/map/src/lib/openlayers-map/open-layers-event-manager.ts
- projects/map/src/lib/openlayers-map/open-layers-tool-manager.ts
- projects/map/src/lib/openlayers-map/openlayers-map.ts
- projects/map/src/lib/openlayers-map/tools/open-layers-map-click-tool.ts
[![HTM-1489](https://badgen.net/badge/JIRA/HTM-1489/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1489) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
HTM-1489: Fixes click tool always being enabled
HTM-1457: Refactored click tool to remove 3D observable for OpenLayersClickTool
[HTM-1489]: https://b3partners.atlassian.net/browse/HTM-1489?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> HTM-1489: Fixes click tool always being enabled

- projects/core/src/lib/components/drawing/drawing-style-form/drawing-style-form.component.ts
- projects/core/src/lib/components/drawing/models/drawing-feature.model.ts
- projects/core/src/lib/map/components/map-drawing-buttons/map-drawing-buttons.component.ts
- projects/core/src/lib/map/models/drawing-feature-type.enum.ts
- projects/core/src/lib/map/services/drawing.service.ts
[![EK-48](https://badgen.net/badge/JIRA/EK-48/pink?icon=jira)](https://b3partners.atlassian.net/browse/EK-48) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
This adds a new IMAGE DrawingFeatureType and associated styling options (`markerImage` and `description`)
see also https://github.com/Tailormap/tailormap-api/pull/1270
[EK-48]: https://b3partners.atlassian.net/browse/EK-48?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> EK-48: Add IMAGE featuretype and related styling options for advanced drawing

- projects/admin-core/src/lib/application/state/application.selectors.ts
- projects/admin-core/src/lib/catalog/helpers/catalog-filter.helper.ts
[![HTM-1590](https://badgen.net/badge/JIRA/HTM-1590/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1590) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
Include 3d tiles services in the selection of the layer tree for the application, instead of selecting a tree twice and concatenating, which caused a bug because the same level nodes where in the displayed tree twice
[HTM-1590]: https://b3partners.atlassian.net/browse/HTM-1590?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> HTM-1590: Select layer tree for application only once

- projects/core/src/lib/components/drawing/drawing-objects-list/drawing-objects-list.component.ts
afterRender() fires also when moving mouse from side panel to map, should only scroll to the selected object when first selected.
> Fix repeatedly scrolling to the same feature 

- projects/api/src/lib/models/attribute-filter.model.ts
- projects/core/src/lib/components/attribute-list/attribute-list-content/attribute-list-content.component.spec.ts
- projects/core/src/lib/components/filter/filter-list-item/filter-list-item.component.ts
- projects/core/src/lib/components/filter/state/filter-component.selectors.ts
- projects/core/src/lib/filter/services/simple-attribute-filter.service.spec.ts
- projects/core/src/lib/filter/state/filter.actions.ts
- projects/core/src/lib/filter/state/filter.reducer.ts
- projects/core/src/lib/filter/state/filter.selectors.ts
- projects/core/src/lib/filter/state/filter.state.ts
- projects/core/src/lib/services/attribute-filter.service.ts
- projects/core/src/lib/state/core.effects.ts
- In the filter state the active filter groups with visible layers and validated filters are kept in a separate list next to the list of all filter groups in the viewer configuration.
- When the visible layers change the filter groups for the visible layers are validated and the list of active groups is updated if needed.
- getDescribeAppLayer$ is called only once per layer if the layer is in multiple groups.
> Improve attribute filter service and state

- projects/core/src/lib/components/edit/edit-dialog/edit-dialog.component.ts
[![HTM-1658](https://badgen.net/badge/JIRA/HTM-1658/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1658) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
[HTM-1658]: https://b3partners.atlassian.net/browse/HTM-1658?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> HTM-1658-fix: reactivate feature info when switching back from edit

- projects/admin-api/src/lib/models/oidc-configuration.model.ts
- projects/admin-api/src/lib/models/upload-category.enum.ts
- projects/admin-core/assets/locale/messages.admin-core.de.xlf
- projects/admin-core/assets/locale/messages.admin-core.en.xlf
- projects/admin-core/assets/locale/messages.admin-core.nl.xlf
- projects/admin-core/src/lib/application/application-edit-styling/application-edit-styling.component.ts
- projects/admin-core/src/lib/oidc/oidc-configuration-form/oidc-configuration-form.component.css
- projects/admin-core/src/lib/oidc/oidc-configuration-form/oidc-configuration-form.component.html
- projects/admin-core/src/lib/oidc/oidc-configuration-form/oidc-configuration-form.component.ts
- projects/admin-core/src/lib/oidc/services/oidc-configuration.service.ts
- projects/admin-core/src/lib/oidc/services/oidc-image-remove.service.ts
- projects/api/src/lib/models/login-configuration.model.ts
- projects/core/src/lib/pages/login/login-form/login-form.component.css
- projects/core/src/lib/pages/login/login-form/login-form.component.html
- projects/core/src/lib/pages/login/login-form/login-form.component.spec.ts
- projects/core/src/lib/pages/login/login-form/login-form.component.ts
[![HTM-1660](https://badgen.net/badge/JIRA/HTM-1660/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1660) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
Changes:
- Larger SSO buttons
- Move Tailormap login to expansion panel if there are SSO links
[HTM-1660]: https://b3partners.atlassian.net/browse/HTM-1660?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> HTM-1660: Change login screen
