docker-compose-cd.yml
docker-compose-pr.yml
docker-compose.yml

- add traefik.enable label to pre-sort for traefik changes
- add restart policy so services come back up after reboot unless stopped

compose file updates

---

projects/api/src/lib/services/tailormap-api-v1-mock.service.ts
projects/api/src/lib/services/tailormap-api-v1.service.ts

related to/to merged after https://github.com/B3Partners/tailormap-api/pull/68

[HTM-243] add extra crs parameter to features call

---

docker/db/docker-entrypoint-initdb.d/3-dump.sql.script
docker/db/docker-entrypoint-initdb.d/3-load-data.sh

HTM-257 Update tailormap-db dump with current state from snapshot.b3pnl / h02

---

projects/core/src/lib/components/feature-info/feature-info-dialog/feature-info-dialog.component.css
projects/core/src/lib/components/feature-info/feature-info-dialog/feature-info-dialog.component.html
projects/core/src/lib/components/feature-info/feature-info-dialog/feature-info-dialog.component.ts
projects/core/src/lib/components/feature-info/feature-info.service.ts
projects/core/src/lib/components/feature-info/feature-info/feature-info.component.ts
projects/core/src/lib/components/feature-info/state/feature-info.reducer.ts
projects/core/src/lib/components/feature-info/state/feature-info.selectors.ts
projects/map/src/lib/map-service/map.service.ts

HTM-260: Remove highlight on layer deactivation & closing feature info
HTM-261: Disable simplification for feature info geometry
HTM-263: Reset current selected index when loading new feature info
HTM-264: Fixed height for feature info and scroll if there is more info

Fixes highlight feature bugs

---

.github/workflows/close-pr.yml
.github/workflows/test-and-deploy.yml

Also:
- extract Node version to use into an env variable.
- change environment cleanup token to cleanup https://github.com/B3Partners/tailormap-viewer/settings/environments on PR close

use current major versions for actions

---

projects/core/src/lib/components/toolbar/clicked-coordinates/clicked-coordinates.component.ts

[HTM-325] Close snackbar on activating a different tool or deactivating the tool

---

angular.json
projects/core/src/lib/components/drawing/create-drawing-button/create-drawing-button.component.ts
projects/core/src/lib/components/drawing/drawing-style-form/drawing-style-form.component.css
projects/core/src/lib/components/drawing/drawing-style-form/drawing-style-form.component.html
projects/core/src/lib/components/drawing/drawing-style-form/drawing-style-form.component.spec.ts
projects/core/src/lib/components/drawing/drawing-style-form/drawing-style-form.component.ts
projects/core/src/lib/components/drawing/drawing/drawing.component.ts
projects/core/src/lib/components/drawing/helpers/drawing.helper.ts
projects/core/src/lib/components/drawing/models/drawing-feature.model.ts
projects/core/src/lib/components/drawing/state/drawing.selectors.ts
projects/core/src/lib/components/feature-info/feature-info/feature-info.component.ts
projects/core/src/lib/components/toolbar/measure/measure.component.ts
projects/map/src/lib/helpers/feature.helper.ts
projects/map/src/lib/helpers/geometry-type.helper.ts
projects/map/src/lib/helpers/map-size.helper.ts
projects/map/src/lib/helpers/map-style.helper.ts
projects/map/src/lib/models/map-style.model.ts
projects/map/src/lib/openlayers-map/tools/open-layers-drawing-tool.ts
projects/map/src/lib/openlayers-map/tools/open-layers-select-tool.ts
projects/shared/src/lib/helpers/index.ts
projects/shared/src/lib/helpers/style.helper.ts
projects/shared/src/lib/services/icons/icon.service.ts
projects/shared/src/lib/shared-imports.module.ts

HTM-312: Add properties for line drawing

---

projects/api/src/lib/mock-data/tailormap-api.mock-data.ts
projects/api/src/lib/models/app-layer.model.ts
projects/api/src/lib/services/tailormap-api-v1-mock.service.ts

see also https://github.com/B3Partners/tailormap-api/pull/142

[HTM-395] Add a `hasAttributes` member to the API's AppLayer

---

projects/core/src/lib/components/feature-info/feature-info.service.spec.ts
projects/core/src/lib/components/feature-info/feature-info.service.ts
projects/core/src/lib/map/state/map.selectors.ts

[HTM-338] Only request feature info when layer has feature type / attributes

---

projects/shared/src/lib/components/color-picker/color-picker.component.html

resolves HTM-392, tested on the same device that reported the problem

[HTM-392] Add a touchend on the color divs so that you can choose colors on Android

---

projects/core/src/lib/components/attribute-list/attribute-list/attribute-list.component.css
projects/core/src/lib/components/attribute-list/attribute-list/attribute-list.component.html

HTM-402: Toggle maximize icons for attribute-list
HTM-404: Fixes minimization for attribute-list

HTM-402: Toggle maximize icons for attribute-list

---

projects/api/src/lib/models/index.ts
projects/api/src/lib/models/sortorder.enum.ts
projects/api/src/lib/services/tailormap-api-v1.service.model.ts
projects/api/src/lib/services/tailormap-api-v1.service.ts

requires https://github.com/B3Partners/tailormap-api/pull/151

[HTM-417] Update features API design with sortBy and sortOrder

---

projects/api/src/lib/models/app-layer.model.ts
projects/api/src/lib/models/layer-hi-dpi-mode.enum.ts
projects/api/src/lib/models/service-hi-dpi-mode.enum.ts
projects/api/src/lib/models/service.model.ts
projects/core/src/lib/map/services/application-map.service.ts
projects/map/src/lib/helpers/ol-layer.helper.ts
projects/map/src/lib/helpers/server-type.helper.ts
projects/map/src/lib/models/wms-layer.model.ts
projects/map/src/lib/models/wmts-layer.model.ts

HTM-48
WIP see https://github.com/B3Partners/tailormap-viewer/pull/93/files

[HTM-48] Use configured hidpi options

---

projects/core/src/lib/components/feature-info/feature-info.service.spec.ts
projects/core/src/lib/components/feature-info/feature-info.service.ts

Use the view resolution to set the feature info distance parameter

---

.gitignore
angular.json
bin/prebuild.js
package-lock.json
package.json

this can be requested in other applications for monitoring eg. the admin version info page
see https://github.com/B3Partners/tailormap-admin/pull/118
resolves HTM-442

[HTM-442] Create a `version.json` file as an asset

---

.gitignore
angular.json
bin/prebuild.js

see https://b3partners.slack.com/archives/DDXNY3AQP/p1661499529213389
please `rm projects/app/src/version.json` to clean up the old generated file

[HTM-442] Move generated `version.json` file to project root

---

projects/core/src/lib/components/attribute-list/state/attribute-list.effects.ts

so the highlight geometry can be projected to the view
resolves HTM-448

[HTM-448] Send CRS with get feature by FID request

---

projects/core/src/lib/components/feature-info/feature-info.service.spec.ts
projects/core/src/lib/components/feature-info/feature-info.service.ts

so the highlight geometry can be projected to the view
resolves HTM-447

[HTM-447] send crs with x and y coordinates

---

projects/api/src/lib/mock-data/tailormap-api.mock-data.ts
projects/api/src/lib/models/index.ts
projects/api/src/lib/models/server-type.enum.ts
projects/api/src/lib/models/service-hi-dpi-mode.enum.ts
projects/api/src/lib/models/service.model.ts
projects/api/src/lib/services/tailormap-api-v1-mock.service.ts
projects/core/src/lib/map/services/application-map.service.ts
projects/core/src/lib/map/state/map.effects.ts
projects/map/src/lib/helpers/ol-layer.helper.ts
projects/map/src/lib/helpers/server-type.helper.ts
projects/map/src/lib/models/wms-layer.model.ts
projects/map/src/public-api.ts

Related to https://github.com/B3Partners/tailormap-api/pull/183

Rename hiDpiMode to serverType and add resolvedServerType

---

projects/core/src/lib/components/feature-info/feature-info.service.ts

see https://b3partners.atlassian.net/browse/HTM-332?focusedCommentId=39146
resolves HTM-332

[HTM-332] Increase the default buffer distance multiplier from 4 to 10

---

projects/core/src/lib/components/legend/legend-layer/legend-layer.component.css
projects/core/src/lib/components/legend/legend-layer/legend-layer.component.html
projects/core/src/lib/components/legend/legend-layer/legend-layer.component.spec.ts
projects/core/src/lib/components/legend/legend-layer/legend-layer.component.ts
projects/core/src/lib/components/legend/legend/legend.component.html
projects/core/src/lib/components/legend/legend/legend.component.spec.ts
projects/core/src/lib/components/legend/legend/legend.component.ts
projects/core/src/lib/components/legend/models/legend-info.model.ts
projects/core/src/lib/components/legend/services/legend.service.ts
projects/map/src/lib/helpers/scale.helper.ts
projects/map/src/lib/models/map-resolution.model.ts
projects/map/src/lib/openlayers-map/openlayers-map.ts
projects/map/src/public-api.ts
projects/shared/src/lib/helpers/url.helper.spec.ts
projects/shared/src/lib/helpers/url.helper.ts

Add SCALE to GetLegendGraphic request and gray out layer title when out of scale

---

.github/workflows/cleanup-and-maintainance.yml
.github/workflows/close-pr.yml
.github/workflows/codeql-analysis.yml
.github/workflows/test-and-deploy.yml
README.md
docker-compose-pr.yml
docker/db/docker-entrypoint-initdb.d/3-load-data.sh

[HTM-470] Upgrade CI to latest/current Ubuntu and docker compose versions

---

projects/api/src/lib/mock-data/tailormap-api.mock-data.ts
projects/api/src/lib/models/unique-values-response.model.ts
projects/api/src/lib/services/tailormap-api-v1-mock.service.ts
projects/api/src/lib/services/tailormap-api-v1.service.model.ts
projects/api/src/lib/services/tailormap-api-v1.service.spec.ts
projects/api/src/lib/services/tailormap-api-v1.service.ts
projects/api/src/lib/services/unique-values.service.spec.ts
projects/api/src/lib/services/unique-values.service.ts
projects/core/src/lib/core.module.ts
projects/core/src/lib/services/load-application.service.spec.ts
projects/core/src/lib/state/core.reducer.spec.ts

Based on https://github.com/B3Partners/tailormap-viewer/pull/167

HTM-460: Added API models + method to get unique values. Merged mock-data and mock-api service.

---

.github/workflows/test-and-deploy.yml

Combine pull and up in 1 command, don't do it quietly to prevent ssh disconnects om main branch

Combine pull and up in 1 command

---

projects/core/assets/tailormap-styles.css
projects/core/src/lib/components/attribute-list/attribute-list-content/attribute-list-content.component.ts
projects/core/src/lib/components/attribute-list/attribute-list-tab-toolbar/attribute-list-tab-toolbar.component.ts
projects/core/src/lib/components/attribute-list/attribute-list/attribute-list.component.css
projects/core/src/lib/components/feature-info/feature-info-dialog/feature-info-dialog.component.css
projects/core/src/lib/components/feature-info/feature-info-dialog/feature-info-dialog.component.html
projects/core/src/lib/components/feature-info/feature-info-dialog/feature-info-dialog.component.ts
projects/core/src/lib/components/menubar/menubar-button/menubar-button.component.css
projects/core/src/lib/components/menubar/menubar-panel/menubar-panel.component.html
projects/core/src/lib/components/menubar/menubar-panel/menubar-panel.component.ts
projects/core/src/lib/components/menubar/menubar.component.css
projects/core/src/lib/components/menubar/menubar.component.html
projects/core/src/lib/components/print/print/print.component.css
projects/core/src/lib/components/toc/toc/toc.component.css
projects/core/src/lib/pages/viewer-app/viewer-app.component.css
projects/core/src/lib/pages/viewer-app/viewer-app.component.ts
projects/shared/src/lib/components/color-picker/color-picker.component.ts
projects/shared/src/lib/components/confirm-dialog/confirm-dialog.service.ts
projects/shared/src/lib/components/dialog/dialog.component.html
projects/shared/src/lib/components/dialog/dialog.component.ts
projects/shared/src/lib/components/dialog/dialog.service.ts
projects/shared/src/lib/components/panel-resizer/panel-resizer.component.ts
projects/shared/src/lib/components/tree/tree.component.ts
projects/shared/src/lib/helpers/browser.helper.ts
projects/shared/src/lib/helpers/css.helper.ts
projects/shared/src/lib/helpers/index.ts
projects/shared/src/lib/shared.module.ts

See [HTM-478](https://b3partners.atlassian.net/browse/HTM-478)

HTM-478: Mobile screen fixes

---

projects/core/src/lib/components/toolbar/simple-search/simple-search.component.css
projects/core/src/lib/components/toolbar/simple-search/simple-search.component.html
projects/core/src/lib/components/toolbar/simple-search/simple-search.component.ts

Also fixes HTM-502: Add hint: Type at least 4 characters to start searching

HTM-501: Show 'no results found' message + search status

---

.github/workflows/test-and-deploy.yml
Dockerfile

see https://github.com/nodejs/node/blob/main/doc/changelogs/CHANGELOG_V16.md#16.18.0

Bump NodeJS from 16.17.1 to 16.18.0

---

.env.template
README.md
docker-compose.yml
docker/db/docker-entrypoint-initdb.d/3-initialize-empty-database.sql.script
docker/db/docker-entrypoint-initdb.d/3-load-data.sh

HTM-531: Add variable to initialize empty config db when starting Docker stack

---

Dockerfile
docker/db/Dockerfile

Update curl/lib/curl to fix CVE-2022-32221, CVE-2022-42915 and CVE-2022-42916

Fix CVE-2022-32221, CVE-2022-42915 and CVE-2022-42916 and setup proper timezone

---

.github/workflows/test-and-deploy.yml

current licenses:
```
└─ $ ▶ npx license-checker --summary
├─ MIT: 924
├─ ISC: 106
├─ Apache-2.0: 38
├─ CC0-1.0: 35
├─ BSD-2-Clause: 34
├─ BSD-3-Clause: 32
├─ 0BSD: 3
├─ (MIT OR Apache-2.0): 2
├─ Unlicense: 2
├─ (MIT AND Zlib): 2
├─ (MIT OR CC0-1.0): 2
├─ Custom: https://github.com/tmcw/jsonlint: 1
├─ Python-2.0: 1
├─ (Apache-2.0 AND MIT): 1
├─ CC-BY-4.0: 1
├─ (MPL-2.0 OR Apache-2.0): 1
├─ BSD*: 1
├─ WTFPL: 1
├─ (BSD-3-Clause OR GPL-2.0): 1
├─ MIT*: 1
├─ CC-BY-3.0: 1
└─ UNLICENSED: 1
```

Deny any GPL licenses / check current licenses

---

projects/api/src/lib/mock-data/tailormap-api.mock-data.ts
projects/api/src/lib/models/app-response.model.ts
projects/api/src/lib/services/tailormap-api-v1-mock.service.ts
projects/api/src/lib/services/tailormap-api-v1.service.model.ts
projects/api/src/lib/services/tailormap-api-v1.service.spec.ts
projects/api/src/lib/services/tailormap-api-v1.service.ts
projects/core/src/lib/services/load-application.service.spec.ts
projects/core/src/lib/services/load-application.service.ts
projects/core/src/lib/state/core.actions.ts
projects/core/src/lib/state/core.effects.ts
projects/core/src/lib/state/core.reducer.ts
projects/core/src/lib/state/core.state.ts

Use with https://github.com/B3Partners/tailormap-api/pull/237

[HTM-127] Components config moved to /app API

---

projects/core/src/lib/components/filter/services/create-filter.service.ts

[HTM-590] Fix hardcoded application id

---

projects/core/src/lib/map/services/application-map.service.ts

On mobile (or while debugging), the map seems to be rendered at least once due to a mistimed resize, causing a stray moveend event, overriding the initial centre + zoom of the map as specified by a bookmark. This fixes that ordering.

core: fix location bookmark ordering

---

projects/api/src/lib/services/tailormap-api-v1.service.spec.ts
projects/api/src/lib/services/tailormap-api-v1.service.ts

Related https://github.com/B3Partners/tailormap-api/pull/284

[HTM-621] Put filter in POST body

---

projects/core/src/lib/filter/helpers/attribute-filter.helper.ts

fix spelling "Smaller than"

---

projects/api/src/lib/models/layer-tree-node.model.ts
projects/core/src/lib/map/bookmark/bookmark.helper.ts
projects/core/src/lib/map/bookmark/bookmark.proto
projects/core/src/lib/map/bookmark/bookmark_pb.ts
projects/core/src/lib/map/helpers/layer-tree-node.helper.ts
projects/core/src/lib/map/models/extended-layer-tree-node.model.ts
projects/core/src/lib/map/services/application-map-bookmark.service.ts
projects/core/src/lib/map/services/application-map.service.ts
projects/core/src/lib/map/state/map.actions.ts
projects/core/src/lib/map/state/map.reducer.ts
projects/core/src/lib/map/state/map.selectors.ts

This stores the list of children of any foreground layer tree node whose contents have been changed from the original.

HTM-640: Layer order bookmark

---

Dockerfile
angular.json

Works with https://github.com/B3Partners/tailormap-api/pull/335

Update output path for admin

---

.github/workflows/close-pr.yml

see https://github.com/B3Partners/tailormap-viewer/commit/197edf6ae1deb9201df6a72ceadc50102e5579f5#r103214849

fix cleanup of composed images

---

.env.template
.github/workflows/test-and-deploy.yml
README.md
docker-compose.db-port.yml
docker-compose.override.yml
docker-compose.yml

Reduce confusion when someone already has PostgreSQL running.

Do not bind PostgreSQL to the host by default, fix some typos

---

projects/admin-api/src/lib/mock-data/tailormap-admin-api.mock-data.ts
projects/admin-api/src/lib/models/application.model.ts
projects/admin-api/src/lib/models/authorization-rules.model.ts
projects/admin-api/src/lib/models/geo-service.model.ts
projects/admin-api/src/lib/models/index.ts
projects/admin-core/src/lib/application/application-edit-settings/application-edit-settings.component.spec.ts
projects/admin-core/src/lib/application/application-form/application-form.component.css
projects/admin-core/src/lib/application/application-form/application-form.component.html
projects/admin-core/src/lib/application/application-form/application-form.component.spec.ts
projects/admin-core/src/lib/application/application-form/application-form.component.ts
projects/admin-core/src/lib/application/application.module.ts
projects/admin-core/src/lib/application/services/application.service.ts
projects/admin-core/src/lib/catalog/catalog-create-buttons/catalog-create-buttons.component.spec.ts
projects/admin-core/src/lib/catalog/geo-service-details/geo-service-details.component.spec.ts
projects/admin-core/src/lib/catalog/geo-service-form-dialog/geo-service-form-dialog.component.spec.ts
projects/admin-core/src/lib/catalog/geo-service-form/geo-service-form.component.css
projects/admin-core/src/lib/catalog/geo-service-form/geo-service-form.component.html
projects/admin-core/src/lib/catalog/geo-service-form/geo-service-form.component.spec.ts
projects/admin-core/src/lib/catalog/geo-service-form/geo-service-form.component.ts
projects/admin-core/src/lib/catalog/models/geo-service-update.model.ts
projects/admin-core/src/lib/shared/components/authorization-edit/authorization-edit.component.css
projects/admin-core/src/lib/shared/components/authorization-edit/authorization-edit.component.html
projects/admin-core/src/lib/shared/components/authorization-edit/authorization-edit.component.ts
projects/admin-core/src/lib/shared/components/shared-admin-components.module.ts
projects/shared/src/lib/shared-imports.module.ts

Pretty complete, but might need a few licks of paint (mostly around being able to deselect all chips):

HTM-705 / HTM-704: Admin authorization UI

---

Dockerfile
projects/admin-api/tsconfig.lib.json
projects/admin-api/tsconfig.lib.prod.json
projects/admin-app/tsconfig.app.json
projects/admin-app/tsconfig.prod.json
projects/admin-core/tsconfig.lib.json
projects/admin-core/tsconfig.lib.prod.json
projects/api/tsconfig.lib.json
projects/api/tsconfig.lib.prod.json
projects/app/tsconfig.app.json
projects/app/tsconfig.prod.json
projects/core/tsconfig.lib.json
projects/core/tsconfig.lib.prod.json
projects/map/tsconfig.lib.json
projects/map/tsconfig.lib.prod.json
projects/shared/tsconfig.lib.json
projects/shared/tsconfig.lib.prod.json
tsconfig.json
tsconfig.prod.json

to prevent warnings from some tools in our CI

remove comments from json files as to make them valid

---

projects/admin-core/src/lib/application/application-form/application-form.component.spec.ts
projects/admin-core/src/lib/application/application-form/application-form.component.ts

default to the first supported CRS from the collection (if there is no default the form initialises with an empty option which does not make sense
resolves HTM-766

[HTM-766] Mandate a valid CRS for the application

---

projects/admin-core/src/lib/application/application-edit-layers/application-edit-layers.component.html
projects/admin-core/src/lib/application/application-edit-layers/application-edit-layers.component.ts
projects/admin-core/src/lib/application/application-edit/application-edit.component.html
projects/admin-core/src/lib/application/application-edit/application-edit.component.spec.ts
projects/admin-core/src/lib/application/application-edit/application-edit.component.ts
projects/admin-core/src/lib/application/application-layer-tree/application-layer-tree.component.ts
projects/admin-core/src/lib/application/helpers/application-model.helper.spec.ts
projects/admin-core/src/lib/application/helpers/application-model.helper.ts
projects/admin-core/src/lib/application/helpers/application-tree.helper.ts
projects/admin-core/src/lib/application/state/application.actions.ts
projects/admin-core/src/lib/application/state/application.reducer.ts
projects/admin-core/src/lib/application/state/application.selectors.ts
projects/admin-core/src/lib/application/state/application.state.ts
projects/shared/src/lib/components/tree/tree.service.ts

HTM-789: Use unique id's for app tree layer nodes
+ Persist the expanded state for application tree's when editing

HTM-789: Use unique id's for app tree layer nodes

---

projects/admin-api/src/lib/mock-data/tailormap-admin-api.mock-data.ts
projects/admin-api/src/lib/models/authorization-rules.model.ts
projects/admin-core/src/lib/shared/components/authorization-edit/authorization-edit.component.ts

Somehow missed this when updating the api-side name.

HTM-791: fix app-authenticated group name

---

projects/admin-api/src/lib/mock-data/tailormap-admin-api.mock-data.ts
projects/admin-api/src/lib/models/app-layer-settings.model.ts
projects/admin-api/src/lib/models/geo-service-layer.model.ts
projects/admin-api/src/lib/models/layer-settings.model.ts
projects/api/src/lib/models/app-layer.model.ts

see also: https://github.com/B3Partners/tailormap-api/pull/476

[HTM-800] Add attribution to AppLayer

---

projects/core/src/lib/pages/viewer-app/viewer-app.component.spec.ts
projects/core/src/lib/pages/viewer-app/viewer-app.component.ts
projects/core/src/lib/state/core.selectors.ts

[HTM-711] Set document.title to app title when loading viewer

---

projects/admin-api/src/lib/models/app-layer-settings.model.ts
projects/admin-core/src/lib/application/application-layer-settings/application-layer-settings.component.html
projects/admin-core/src/lib/application/application-layer-settings/application-layer-settings.component.ts
projects/admin-core/src/lib/catalog/layer-settings-form/layer-settings-form.component.html
projects/admin-core/src/lib/catalog/layer-settings-form/layer-settings-form.component.ts
projects/core/assets/openlayers.css
projects/core/src/lib/map/services/application-map.service.ts
projects/map/src/lib/helpers/ol-layer.helper.ts
projects/map/src/lib/models/layer.model.ts
projects/map/src/lib/openlayers-map/openlayers-map.ts

[HTM-798]: https://b3partners.atlassian.net/browse/HTM-798?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[HTM-801]: https://b3partners.atlassian.net/browse/HTM-801?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
resolves HTM-521
[HTM-799]: https://b3partners.atlassian.net/browse/HTM-799?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[HTM-521] Support adding an attribution to layers

---

projects/admin-core/src/lib/user/group-edit/group-edit.component.spec.ts
projects/admin-core/src/lib/user/group-edit/group-edit.component.ts

see also https://github.com/B3Partners/tailormap-api/pull/478

[HTM-776] Update the already obvious warning message to be even more obvious

---

projects/admin-core/src/lib/catalog/catalog-tree/catalog-tree.component.ts

see https://github.com/B3Partners/tailormap-viewer/pull/398/files#r1222637148 / HTM-803 /

Remove console.log statement from catalog-tree.component.ts

---

projects/api/src/lib/services/tailormap-api-v1.service.model.ts
projects/core/src/lib/components/attribute-list/state/attribute-list.effects.ts
projects/core/src/lib/components/feature-info/feature-info.service.ts

depends on https://github.com/B3Partners/tailormap-api/pull/523
resolves HTM-875

[HTM-875] Remove the superfluous crs parameter from the `/features` call

---

projects/admin-api/src/lib/models/index.ts
projects/admin-api/src/lib/models/jdbc-connection-properties.model.ts
projects/admin-api/src/lib/models/jdbc-database-type.enum.ts
projects/admin-api/src/lib/models/jdbc-database-type.ts
projects/admin-core/src/lib/catalog/feature-source-details/feature-source-details.component.spec.ts
projects/admin-core/src/lib/catalog/feature-source-form/feature-source-form.component.html
projects/admin-core/src/lib/catalog/feature-source-form/feature-source-form.component.ts

resolves HTM-886
requires https://github.com/B3Partners/tailormap-api/pull/535

[HTM-886] Allow providing database connection parameters and provide default options when choosing a database flavour

---

projects/admin-core/src/lib/interceptors/security.interceptor.ts
projects/admin-core/src/lib/pages/admin-login-page/admin-login-page.component.html
projects/admin-core/src/lib/pages/admin-login-page/admin-login-page.component.ts
projects/admin-core/src/lib/state/admin-core.actions.ts
projects/admin-core/src/lib/state/admin-core.reducer.ts
projects/admin-core/src/lib/state/admin-core.selectors.ts
projects/admin-core/src/lib/state/admin-core.state.ts
projects/admin-core/src/lib/user/services/group.service.ts
projects/admin-core/src/lib/user/services/user.service.ts
projects/api/src/lib/services/tailormap-security-api-v1.service.ts
projects/core/src/lib/interceptors/security.interceptor.ts
projects/core/src/lib/pages/login/login.component.html
projects/core/src/lib/pages/login/login.component.ts
projects/core/src/lib/state/core.actions.ts
projects/core/src/lib/state/core.reducer.ts
projects/core/src/lib/state/core.selectors.ts
projects/core/src/lib/state/core.state.ts
projects/shared/src/lib/components/login-form/login-form.component.spec.ts
projects/shared/src/lib/components/login-form/login-form.component.ts

[HTM-854] Add error message to login form to indicate lack of roles

---

projects/admin-core/src/lib/catalog/feature-source-details/feature-source-details.component.spec.ts
projects/admin-core/src/lib/test-helpers/test-save.helper.ts

Should fix reliability issues.

feature-source-details: Use jest fake timers for test

---

docker-compose.traefik.yml

HTM-980: Added HSTS headers

---

.github/workflows/test-and-deploy.yml

see https://github.com/codecov/codecov-action/releases

Update Codecov action to v4

---

projects/admin-api/src/lib/models/jdbc-database-type.ts

related https://github.com/B3Partners/tailormap-api/pull/720

[HTM-1003] Add `ApplicationName=tailormap-api` to any PostgreSQL connection

---

projects/admin-core/assets/locale/messages.admin-core.en.xlf
projects/admin-core/assets/locale/messages.admin-core.nl.xlf
projects/admin-core/src/lib/application/application-create/application-create.component.html
projects/admin-core/src/lib/application/application-create/application-create.component.ts
projects/admin-core/src/lib/application/application-edit-settings/application-edit-settings.component.html
projects/admin-core/src/lib/application/application-edit-settings/application-edit-settings.component.ts
projects/admin-core/src/lib/application/application-edit/application-edit.component.html
projects/admin-core/src/lib/application/application-edit/application-edit.component.ts
projects/admin-core/src/lib/application/application-form/application-form.component.html
projects/admin-core/src/lib/application/application-form/application-form.component.spec.ts
projects/admin-core/src/lib/application/application-form/application-form.component.ts
projects/admin-core/src/lib/application/state/application.actions.ts
projects/admin-core/src/lib/application/state/application.reducer.ts
projects/admin-core/src/lib/application/state/application.selectors.ts
projects/admin-core/src/lib/application/state/application.state.ts

It would be good to also check this on the backend / make name a UNIQUE field in the database?

HTM-1025: Application name should be unique

---

projects/admin-api/src/lib/models/config.model.ts
projects/admin-core/src/lib/config/services/config.service.ts

Config jsonValue is not meant to be stringified

---

.github/workflows/test-and-deploy.yml
Dockerfile
package-lock.json
package.json

see https://github.com/nodejs/node/blob/main/doc/changelogs/CHANGELOG_V20.md#20.11.1

Bump NodeJS from 20.11.0 to 20.11.1

---

projects/core/assets/icons/fullscreen.svg
projects/core/assets/icons/fullscreen_exit.svg
projects/shared/src/lib/components/dialog/dialog.component.css
projects/shared/src/lib/components/dialog/dialog.component.html
projects/shared/src/lib/components/dialog/dialog.component.ts
projects/shared/src/lib/services/icons/icon.service.ts

Not currently used in the viewer, but can be passed as an option to enable dialogs to be fullscreen

Add option for full-screen dialogs

---

.github/workflows/test-and-deploy.yml
README.md
docker-compose.network.yml
docker-compose.traefik.yml
docker-compose.yml

related https://github.com/B3Partners/containers/pull/504
[HTM-1063]: https://b3partners.atlassian.net/browse/HTM-1063?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[HTM-1074]: https://b3partners.atlassian.net/browse/HTM-1074?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[HTM-1063] Add preconfigured Solr instance to compose stack

---

projects/admin-core/src/lib/oidc/oidc-configuration-form/oidc-configuration-form.component.html

HTM-1104: use tm-admin-password-field component for client-secret

---

.github/workflows/test-and-deploy.yml
docker-compose.yml

HTM-1139: Deploy Solr service on deployment of snapshot

---

projects/admin-core/assets/locale/messages.admin-core.nl.xlf
projects/core/assets/locale/messages.core.nl.xlf
projects/shared/assets/locale/messages.shared.nl.xlf

HTM-1138: 🇳🇱 Update and fix Dutch translations 

---

projects/admin-core/assets/locale/messages.admin-core.de.xlf
projects/core/assets/locale/messages.core.de.xlf
projects/shared/assets/locale/messages.shared.de.xlf

HTM-1137: 🇩🇪 Update  and fix German translations

---

projects/admin-core/assets/locale/messages.admin-core.de.xlf
projects/admin-core/assets/locale/messages.admin-core.en.xlf
projects/admin-core/assets/locale/messages.admin-core.nl.xlf
projects/admin-core/src/lib/application/application-layer-tree/application-layer-tree-node/application-layer-tree-node.component.html

HTM-1148: 🇳🇱 🇩🇪 Popup menu for adding/removing/renaming subfolder is not translated to Dutch/German

---

.all-contributorsrc
.env.template
.github/workflows/cleanup-and-maintainance.yml
.github/workflows/test-and-deploy.yml
.github/workflows/trivy.yml
Dockerfile
README.md
docker-compose.yml

companion to https://github.com/B3Partners/tailormap-api/pull/909

HTM-1173: Rename docker images to use the new Tailormap organisation

---

.github/workflows/cleanup-and-maintainance.yml
.github/workflows/codeql-analysis.yml
.github/workflows/deploy-embed-test.yml
.github/workflows/process-test-results.yml
.github/workflows/release-drafter.yml
.github/workflows/test-and-deploy.yml
.github/workflows/trivy.yml
README.md

[![HTM-1169](https://badgen.net/badge/JIRA/HTM-1169/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1169) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
[HTM-1169]: https://b3partners.atlassian.net/browse/HTM-1169?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

HTM-1169: Update tailormap-viewer CI/CD workflows to make them work again

---

projects/admin-api/package.json
projects/admin-core/package.json
projects/api/package.json
projects/core/package.json
projects/map/package.json
projects/shared/package.json

[![HTM-1194](https://badgen.net/badge/JIRA/HTM-1194/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1194) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
see also https://github.com/Tailormap/tailormap-api/pull/918

HTM-1194: Bump to version 11.4.0

---

projects/core/src/lib/components/legend/legend-layer/legend-layer.component.spec.ts
projects/core/src/lib/components/legend/legend/legend.component.spec.ts
projects/core/src/lib/components/toc/toc-node-details/layer-details/layer-details.component.spec.ts
projects/core/src/lib/components/toc/toc-node-details/toc-node-details.component.spec.ts
projects/shared/src/lib/components/legend-image/legend-image.component.css
projects/shared/src/lib/components/legend-image/legend-image.component.html
projects/shared/src/lib/components/legend-image/legend-image.component.spec.ts
projects/shared/src/lib/components/legend-image/legend-image.component.ts

[![HTM-1147](https://badgen.net/badge/JIRA/HTM-1147/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1147) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
[HTM-1147]: https://b3partners.atlassian.net/browse/HTM-1147?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

HTM-1147: Reduce flickering and keep scrollbar pos when viewing legend

---

projects/core/src/lib/components/filter/services/spatial-filter-crud.service.spec.ts
projects/core/src/lib/components/filter/services/spatial-filter-crud.service.ts
projects/core/src/lib/components/print/print.service.ts

[![HTM-1200](https://badgen.net/badge/JIRA/HTM-1200/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1200) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
[HTM-1200]: https://b3partners.atlassian.net/browse/HTM-1200?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

HTM-1200: Fixes printing when no background is selected

---

projects/core/src/lib/components/filter/services/spatial-filter-crud.service.spec.ts
projects/core/src/lib/components/filter/services/spatial-filter-crud.service.ts
projects/core/src/lib/components/print/print.service.ts
projects/core/src/lib/services/map-pdf/map-pdf.service.ts
projects/core/src/lib/shared/helpers/image.helper.ts

[![HTM-1156](https://badgen.net/badge/JIRA/HTM-1156/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1156) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)

HTM-1156: Use application logo if set for printing

---

.github/workflows/codeql.yml

CodeQL no longer requires building

Update and rename codeql-analysis.yml to codeql.yml

---

projects/admin-core/assets/icons/admin/logs.svg
projects/admin-core/assets/locale/messages.admin-core.de.xlf
projects/admin-core/assets/locale/messages.admin-core.en.xlf
projects/admin-core/assets/locale/messages.admin-core.nl.xlf
projects/admin-core/src/lib/admin-core-routing.module.ts
projects/admin-core/src/lib/admin-core.module.ts
projects/admin-core/src/lib/pages/logs-page/logs-page.component.css
projects/admin-core/src/lib/pages/logs-page/logs-page.component.html
projects/admin-core/src/lib/pages/logs-page/logs-page.component.ts
projects/admin-core/src/lib/pages/pages.module.ts
projects/admin-core/src/lib/routes.ts
projects/admin-core/src/lib/templates/admin-template/navigation/navigation.component.html
projects/admin-core/src/lib/templates/admin-template/navigation/navigation.component.ts

[![HTM-1162](https://badgen.net/badge/JIRA/HTM-1162/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1162) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
[HTM-1162]: https://b3partners.atlassian.net/browse/HTM-1162?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

HTM-1162: Show logfile

---

.github/workflows/trivy.yml

[![HTM-1208](https://badgen.net/badge/JIRA/HTM-1208/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1208) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
using https://github.com/yogeshlonkar/trivy-cache-action
[HTM-1208]: https://b3partners.atlassian.net/browse/HTM-1208?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

HTM-1208: Add caching for Trivy

---

projects/admin-core/src/lib/admin-core.module.ts
projects/admin-core/src/lib/shared/services/admin-auth.service.ts
projects/api/src/lib/services/authenticated-user.service.ts
projects/api/src/lib/services/tailormap-api.constants.ts
projects/app/src/app/app.module.ts
projects/shared/src/lib/components/confirm-dialog/confirm-dialog.component.html
projects/shared/src/lib/components/confirm-dialog/confirm-dialog.component.spec.ts
projects/shared/src/lib/components/confirm-dialog/confirm-dialog.component.ts
projects/shared/src/lib/components/confirm-dialog/confirm-dialog.service.ts

[![HTM-1154](https://badgen.net/badge/JIRA/HTM-1154/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1154) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
[HTM-1154]: https://b3partners.atlassian.net/browse/HTM-1154?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

HTM-1154: Check if user is logged in using interval + fixed interceptor

---

.github/workflows/test-and-deploy.yml

[![HTM-1215](https://badgen.net/badge/JIRA/HTM-1215/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1215) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)

HTM-1215: Upload test results to Codecov

---

.gitignore
package.json
projects/api/src/lib/models/feature.model.ts
projects/core/src/lib/components/filter/services/filter-features.service.ts
projects/core/src/lib/components/filter/spatial-filter-form/spatial-filter-form.component.spec.ts
projects/core/src/lib/components/filter/spatial-filter-form/spatial-filter-form.component.ts
projects/core/src/lib/components/filter/state/filter-component.selectors.ts
projects/map/src/lib/helpers/buffer.helper.ts
projects/map/src/lib/helpers/map-style.helper.ts
projects/map/src/lib/models/map-style.model.ts
projects/map/src/public-api.ts
projects/map/src/typings.d.ts
setup-jest.ts

[![HTM-896](https://badgen.net/badge/JIRA/HTM-896/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-896) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
[HTM-896]: https://b3partners.atlassian.net/browse/HTM-896?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

HTM-896: Lazy load JSTS by moving buffering to earlier in de process

---

projects/admin-api/src/lib/models/search-index.model.ts
projects/admin-api/src/lib/models/taskschedule.model.ts

[![HTM-1255](https://badgen.net/badge/JIRA/HTM-1255/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1255) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
depends on https://github.com/Tailormap/tailormap-api/pull/991
[HTM-1255]: https://b3partners.atlassian.net/browse/HTM-1255?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

HTM-1255: Add the possibility to define a schedule on a search index

---

projects/admin-core/src/lib/admin-core.module.ts
projects/core/assets/locale/messages.core.de.xlf
projects/core/assets/locale/messages.core.en.xlf
projects/core/assets/locale/messages.core.nl.xlf
projects/core/src/lib/core.module.ts
projects/core/src/lib/services/user-login-check.service.ts
projects/shared/src/lib/components/about-dialog/about-dialog.component.spec.ts

[![HTM-1262](https://badgen.net/badge/JIRA/HTM-1262/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1262) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
[HTM-1262]: https://b3partners.atlassian.net/browse/HTM-1262?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

HTM-1262: Add login check to viewer as well

---

projects/admin-api/src/lib/models/index.ts
projects/admin-api/src/lib/models/search-index-ping-response.model.ts
projects/admin-api/src/lib/services/tailormap-admin-api-v1-mock.service.ts
projects/admin-api/src/lib/services/tailormap-admin-api-v1-service.model.ts
projects/admin-api/src/lib/services/tailormap-admin-api-v1.service.ts
projects/admin-core/assets/locale/messages.admin-core.de.xlf
projects/admin-core/assets/locale/messages.admin-core.en.xlf
projects/admin-core/assets/locale/messages.admin-core.nl.xlf
projects/admin-core/src/lib/pages/search-index-page/search-index-page.component.html
projects/admin-core/src/lib/pages/search-index-page/search-index-page.component.ts

[![HTM-1260](https://badgen.net/badge/JIRA/HTM-1260/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1260) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
[HTM-1260]: https://b3partners.atlassian.net/browse/HTM-1260?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

HTM-1260: Check Solr availability and show error if not available

---

projects/api/src/lib/mock-data/tailormap-api.mock-data.ts
projects/api/src/lib/models/service.model.ts
projects/core/assets/locale/messages.core.de.xlf
projects/core/assets/locale/messages.core.en.xlf
projects/core/assets/locale/messages.core.nl.xlf
projects/core/src/lib/components/feature-info/feature-info.module.ts
projects/core/src/lib/services/application-bookmark/application-bookmark-fragments.ts
projects/core/src/lib/services/application-bookmark/application-bookmark.service.ts
projects/core/src/lib/services/application-bookmark/bookmark-fragment-handlers/bookmark-fragment-handler-service.model.ts
projects/core/src/lib/services/application-bookmark/bookmark-fragment-handlers/readable-visibility-bookmark-handler.service.spec.ts
projects/core/src/lib/services/application-bookmark/bookmark-fragment-handlers/readable-visibility-bookmark-handler.service.ts
projects/core/src/lib/services/bookmark/bookmark.service.ts

[![HTM-1249](https://badgen.net/badge/JIRA/HTM-1249/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1249) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
[HTM-1249]: https://b3partners.atlassian.net/browse/HTM-1249?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

HTM-1249: Allow service+layername in URL to start with that layer only

---

docker-compose.yml

[![HTM-1276](https://badgen.net/badge/JIRA/HTM-1276/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1276) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
[HTM-1276]: https://b3partners.atlassian.net/browse/HTM-1276?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

HTM-1276: Bump Solr version from 9.6.1 to 9.7.0

---

docker-compose.yml

[![HTM-1277](https://badgen.net/badge/JIRA/HTM-1277/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1277) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)

HTM-1277: Bump postgresql from postgres:15.7-alpine3.18 to postgres:15.8-alpine3.20

---

projects/core/src/lib/layout/base-layout/base-layout.component.css
projects/map/src/lib/map/map.component.css
projects/map/src/lib/map/map.component.html
projects/map/src/lib/map/map.component.ts
projects/map/src/lib/openlayers-map/openlayers-map.ts
projects/shared/assets/locale/messages.shared.de.xlf
projects/shared/assets/locale/messages.shared.en.xlf
projects/shared/assets/locale/messages.shared.nl.xlf
projects/shared/src/lib/helpers/browser.helper.ts
projects/shared/src/lib/helpers/index.ts
projects/shared/src/lib/helpers/overlay.helper.ts

[![HTM-1100](https://badgen.net/badge/JIRA/HTM-1100/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1100) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)

HTM-1100: Add overlay when scrolling on map when TM is in an iframe

---

projects/map/src/lib/helpers/map-size.helper.spec.ts
projects/map/src/lib/helpers/map-size.helper.ts

[![HTM-1275](https://badgen.net/badge/JIRA/HTM-1275/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1275) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)

HTM-1275: Measure tool adjusted distance threshold from 100m to 1000m

---

projects/admin-core/src/lib/pages/application-page/application-page.component.html
projects/admin-core/src/lib/pages/catalog-page/catalog-page.component.html
projects/admin-core/src/lib/pages/form-page/form-page.component.html
projects/admin-core/src/lib/pages/groups-page/groups-page.component.html
projects/admin-core/src/lib/pages/search-index-page/search-index-page.component.html
projects/admin-core/src/lib/pages/user-admin-page/user-admin-page.component.html
projects/admin-core/src/lib/templates/admin-page-template/admin-page-template.component.css
projects/admin-core/src/lib/templates/admin-page-template/admin-page-template.component.html
projects/admin-core/src/lib/templates/admin-page-template/admin-page-template.component.ts
projects/admin-core/src/lib/templates/admin-template/admin-template.component.css
projects/admin-core/src/lib/templates/templates.module.ts
projects/core/src/lib/components/attribute-list/attribute-list-table/attribute-list-table.component.css
projects/core/src/lib/components/attribute-list/attribute-list-table/attribute-list-table.component.html
projects/core/src/lib/components/toc/toc-node-details/toc-node-details.component.html
projects/core/src/lib/shared/components/bottom-panel/bottom-panel.component.html
projects/shared/src/lib/components/panel-resizer/panel-resizer.component.css
projects/shared/src/lib/components/panel-resizer/panel-resizer.component.html
projects/shared/src/lib/components/panel-resizer/panel-resizer.component.ts

[![HTM-1267](https://badgen.net/badge/JIRA/HTM-1267/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1267) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)

HTM-1267: Add resizer to admin to grow/shrink the tree/list

---

projects/admin-core/assets/locale/messages.admin-core.de.xlf
projects/admin-core/assets/locale/messages.admin-core.en.xlf
projects/admin-core/assets/locale/messages.admin-core.nl.xlf
projects/admin-core/src/lib/catalog/feature-type-attributes/feature-type-attributes.component.css
projects/admin-core/src/lib/catalog/feature-type-attributes/feature-type-attributes.component.html
projects/admin-core/src/lib/catalog/feature-type-attributes/feature-type-attributes.component.ts

[![HTM-1233](https://badgen.net/badge/JIRA/HTM-1233/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1233) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)

HTM-1233: Allow to drag multiple rows when reordering feature attributes

---

.github/workflows/test-and-deploy.yml
Dockerfile
README.md
package-lock.json
package.json

[![HTM-1294](https://badgen.net/badge/JIRA/HTM-1294/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1294) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)

HTM-1294: Upgrade NodeJS runtime to 22.x (new LTS)

---

projects/admin-core/src/lib/catalog/feature-type-attributes/feature-type-attributes.component.html

[![HTM-1232](https://badgen.net/badge/JIRA/HTM-1232/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1232) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
[HTM-1232]: https://b3partners.atlassian.net/browse/HTM-1232?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

HTM-1232: Gray out entire row when attribute is disabled

---

projects/admin-core/src/lib/templates/admin-page-template/admin-page-template.component.css
projects/admin-core/src/lib/templates/admin-page-template/admin-page-template.component.html
projects/admin-core/src/lib/templates/admin-template/admin-template.component.css
projects/shared/src/lib/components/panel-resizer/panel-resizer.component.css
projects/shared/src/lib/components/panel-resizer/panel-resizer.component.html
projects/shared/src/lib/components/panel-resizer/panel-resizer.component.ts

[![HTM-1267](https://badgen.net/badge/JIRA/HTM-1267/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1267) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)

HTM-1267: Improved design for resizer for side bar resizing

---

projects/admin-core/src/lib/form/form-edit-field/form-edit-field.component.ts

[![HTM-1312](https://badgen.net/badge/JIRA/HTM-1312/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1312) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)

HTM-1312: Prevent choice list from being cleared when form is opened

---

projects/admin-core/src/lib/templates/admin-page-template/admin-page-template.component.css
projects/admin-core/src/lib/templates/admin-template/admin-template.component.css

[![HTM-1314](https://badgen.net/badge/JIRA/HTM-1314/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1314) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
[HTM-1314]: https://b3partners.atlassian.net/browse/HTM-1314?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

HTM-1314: Fixes settings page layout

---

projects/admin-core/src/lib/catalog/feature-type-attributes/feature-type-attributes.component.html
projects/admin-core/src/lib/catalog/feature-type-attributes/feature-type-attributes.component.ts

[![HTM-1233](https://badgen.net/badge/JIRA/HTM-1233/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1233) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)

HTM-1233: When re-ordering a group of rows dragging is improved

---

projects/admin-core/src/lib/search-index/services/search-index.service.ts

[![HTM-1325](https://badgen.net/badge/JIRA/HTM-1325/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1325) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
[HTM-1325]: https://b3partners.atlassian.net/browse/HTM-1325?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

HTM-1325: Show error message when search indexing fails

---

projects/core/src/lib/components/index.ts
projects/core/src/lib/components/toolbar/state/toolbar.effects.ts
projects/core/src/lib/components/toolbar/toolbar.service.ts

[![HTM-1248](https://badgen.net/badge/JIRA/HTM-1248/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1248) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)

HTM-1248: Use service to manage crosshair cursor on map for toolbar

---

README.md

[![HTM-1242](https://badgen.net/badge/JIRA/HTM-1242/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1242) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
[HTM-1242]: https://b3partners.atlassian.net/browse/HTM-1242?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

HTM-1242: remove arm64 build instructions

---

projects/admin-core/assets/locale/messages.admin-core.de.xlf
projects/admin-core/assets/locale/messages.admin-core.en.xlf
projects/admin-core/assets/locale/messages.admin-core.nl.xlf
projects/admin-core/src/lib/search-index/search-index-scheduling/search-index-scheduling.component.css
projects/admin-core/src/lib/search-index/search-index-scheduling/search-index-scheduling.component.html
projects/admin-core/src/lib/search-index/search-index-scheduling/search-index-scheduling.component.ts
projects/admin-core/src/lib/tasks/task-details-row/task-details-row.component.ts
projects/admin-core/src/lib/tasks/task-details/task-details.component.html
projects/api/src/lib/services/application-feature-switch.service.ts

[![HTM-1324](https://badgen.net/badge/JIRA/HTM-1324/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1324) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
[HTM-1324]: https://b3partners.atlassian.net/browse/HTM-1324?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

HTM-1324 (revised): Added translation for 'Description*'

---

projects/admin-core/assets/locale/messages.admin-core.de.xlf
projects/admin-core/assets/locale/messages.admin-core.en.xlf
projects/admin-core/assets/locale/messages.admin-core.nl.xlf
projects/admin-core/src/lib/search-index/services/search-index.service.ts

[![HTM-1352](https://badgen.net/badge/JIRA/HTM-1352/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1352) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
[HTM-1352]: https://b3partners.atlassian.net/browse/HTM-1352?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

HTM-1352: update notification message

---

docker-compose.yml

related to https://b3partners.atlassian.net/browse/HTM-1332

HTM-1353: Add some production-ready Solr options

---

projects/core/src/lib/components/toolbar/simple-search/simple-search.service.ts

[![HTM-1326](https://badgen.net/badge/JIRA/HTM-1326/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1326) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)

HTM-1326: fix PDOK Address search fails when SOLR search index query returns an error or SOLR is unavailable

---

projects/core/src/lib/components/toolbar/simple-search/simple-search.service.ts
projects/core/src/lib/shared/components/dialog/dialog.service.ts

[![HTM-1354](https://badgen.net/badge/JIRA/HTM-1354/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1354) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
[HTM-1354]: https://b3partners.atlassian.net/browse/HTM-1354?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

HTM-1354: Fixes issue in embedded viewer where search would break

---

projects/admin-core/src/lib/form/form-edit-field/form-edit-field.component.html
projects/admin-core/src/lib/form/form-edit-field/form-edit-field.component.ts

Add extra row if <Enter> is pressed in last field

HTM-1292: Do not remove row when pressing <Enter>.

---

projects/admin-core/src/lib/application/application-layer-tree/application-layer-tree.component.html
projects/admin-core/src/lib/application/helpers/application-tree.helper.ts
projects/shared/src/lib/components/tree/tree.component.html
projects/shared/src/lib/components/tree/tree.component.ts

[![HTM-1234](https://badgen.net/badge/JIRA/HTM-1234/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1234) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
[HTM-1234]: https://b3partners.atlassian.net/browse/HTM-1234?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

HTM-1234: Prevent root collapse. Expand/collapse levels below root

---

.github/workflows/test-and-deploy.yml
README.md

[![HTM-1377](https://badgen.net/badge/JIRA/HTM-1377/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1377) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)

HTM-1377: remove dependency track buildsteps tailormap-viewer

---

projects/core/src/lib/components/toolbar/simple-search/simple-search.component.css
projects/core/src/lib/components/toolbar/simple-search/simple-search.component.html
projects/core/src/lib/components/toolbar/simple-search/simple-search.component.ts
projects/shared/src/lib/helpers/htmlify.helper.spec.ts
projects/shared/src/lib/helpers/htmlify.helper.ts

[![HTM-1370](https://badgen.net/badge/JIRA/HTM-1370/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1370) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
[HTM-1370]: https://b3partners.atlassian.net/browse/HTM-1370?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

HTM-1370: Change search component lay-out when more than one search index can be used

---

projects/core/src/lib/pages/login/login-form/login-form.component.css
projects/core/src/lib/pages/login/login-form/login-form.component.html
projects/core/src/lib/pages/login/login-form/login-form.component.ts
projects/shared/assets/locale/messages.shared.de.xlf
projects/shared/assets/locale/messages.shared.en.xlf
projects/shared/assets/locale/messages.shared.nl.xlf

[![HTM-1391](https://badgen.net/badge/JIRA/HTM-1391/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1391) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
[HTM-1391]: https://b3partners.atlassian.net/browse/HTM-1391?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

HTM-1391: Updated login screen layout, moved SSO buttons to top

---

projects/admin-core/src/lib/catalog/services/feature-source.service.ts
projects/admin-core/src/lib/shared/services/admin-sse.service.ts

[![HTM-1397](https://badgen.net/badge/JIRA/HTM-1397/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1397) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
injecting the service will enable task progress tracking, either for all tasks or a specific task
[HTM-1397]: https://b3partners.atlassian.net/browse/HTM-1397?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

HTM-1397: introduce the task-progress event in the AdminSseService

---

projects/admin-core/assets/locale/messages.admin-core.de.xlf
projects/admin-core/src/lib/tasks/task-details-row/task-details-row.component.ts

[![HTM-1398](https://badgen.net/badge/JIRA/HTM-1398/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1398) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
companion to https://github.com/Tailormap/tailormap-api/pull/1102
[HTM-1398]: https://b3partners.atlassian.net/browse/HTM-1398?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

HTM-1398: refactor task keys

---

projects/admin-core/src/lib/search-index/search-index-form/search-index-form.component.html
projects/admin-core/src/lib/search-index/search-index-form/search-index-form.component.ts

[![HTM-1361](https://badgen.net/badge/JIRA/HTM-1361/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1361) 
show progress if/when a scheduled indexing task is running, note that due to design decisions tasks without schedule won't show progress and the progress reported depends on the value of the configuration parameter `tailormap-api.solr-batch-size` progress is reported per batch
[HTM-1361]: https://b3partners.atlassian.net/browse/HTM-1361?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

HTM-1361: handle index tasks progress events in the admin frontend

---

projects/admin-core/src/lib/user/user-edit/user-edit.component.spec.ts
projects/admin-core/src/lib/user/user-form/user-form.component.html
projects/admin-core/src/lib/user/user-form/user-form.component.spec.ts
projects/admin-core/src/lib/user/user-form/user-form.component.ts
projects/core/src/lib/shared/components/dialog/dialog.component.html

[![HTM-1408](https://badgen.net/badge/JIRA/HTM-1408/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1408) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
[HTM-1408]: https://b3partners.atlassian.net/browse/HTM-1408?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

HTM-1408: Added notes to user form

---

projects/admin-core/src/lib/catalog/feature-type-form/feature-type-form.component.html
projects/admin-core/src/lib/catalog/feature-type-template/feature-type-template.component.html
projects/admin-core/src/lib/catalog/feature-type-template/feature-type-template.component.ts
projects/core/src/lib/components/feature-info/feature-info-template-renderer/feature-info-template-renderer.component.ts
projects/shared/src/lib/components/markdown-editor/markdown-source-editor/markdown-source-editor.component.html
projects/shared/src/lib/components/markdown-editor/markdown-source-editor/markdown-source-editor.component.ts
projects/shared/src/lib/helpers/markdown.helper.spec.ts
projects/shared/src/lib/helpers/markdown.helper.ts

HTM-1414: Fixes Markdown editor preview
HTM-1417: Replace null values by empty string in template

HTM-1414: Fixes Markdown editor preview

---

projects/admin-core/src/lib/user/group-form/group-form.component.html
projects/admin-core/src/lib/user/group-form/group-form.component.ts
projects/admin-core/src/lib/user/user-form/user-form.component.html
projects/admin-core/src/lib/user/user-form/user-form.component.ts
projects/shared/src/lib/components/markdown-editor/markdown-source-editor/markdown-source-editor.component.ts

HTM-1414: Add inserted variables instead of replacing
HTM-1408: Added max-length for user/group notes field

Fixes HTM-1414 & HTM-1408

---

projects/admin-core/src/lib/search-index/search-index-scheduling/search-index-scheduling.component.ts

[![HTM-1427](https://badgen.net/badge/JIRA/HTM-1427/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1427) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
The cron expression for 'Every week monday at 18:00' was incorrect
[HTM-1427]: https://b3partners.atlassian.net/browse/HTM-1427?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

HTM-1427: admin frontend uses incorrect cron expression for Monday evening

---

projects/admin-core/src/lib/application/application-layer-attribute-settings/application-layer-attribute-settings.component.html
projects/admin-core/src/lib/application/application-layer-attribute-settings/application-layer-attribute-settings.component.ts
projects/admin-core/src/lib/application/application-layer-settings/application-layer-settings.component.ts

Also show primary key icon in application layer attribute settings

---

projects/admin-api/src/lib/models/feature-type.model.ts
projects/admin-core/assets/locale/messages.admin-core.de.xlf
projects/admin-core/assets/locale/messages.admin-core.en.xlf
projects/admin-core/assets/locale/messages.admin-core.nl.xlf
projects/admin-core/src/lib/catalog/feature-type-details/feature-type-details.component.ts
projects/admin-core/src/lib/catalog/feature-type-form/feature-type-form.component.html
projects/admin-core/src/lib/catalog/feature-type-form/feature-type-form.component.spec.ts
projects/admin-core/src/lib/catalog/feature-type-form/feature-type-form.component.ts
projects/admin-core/src/lib/catalog/helpers/extended-catalog-model.helper.ts
projects/admin-core/src/lib/catalog/models/extended-feature-source.model.ts
projects/admin-core/src/lib/catalog/state/catalog.selectors.ts
projects/shared/src/lib/components/error-message/error-message.component.html
projects/shared/src/lib/components/error-message/error-message.component.ts

[![HTM-1442](https://badgen.net/badge/JIRA/HTM-1442/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1442) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
Requires [tailormap-api#1160](https://github.com/Tailormap/tailormap-api/pull/1160)
[HTM-1442]: https://b3partners.atlassian.net/browse/HTM-1442?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

HTM-1442: show messages about feature type being editable or not

---

projects/admin-api/src/lib/mock-data/tailormap-admin-api.mock-data.ts
projects/admin-api/src/lib/models/admin-server-type.model.ts
projects/admin-api/src/lib/models/geo-service-settings.model.ts
projects/admin-api/src/lib/models/index.ts
projects/admin-core/assets/locale/messages.admin-core.de.xlf
projects/admin-core/assets/locale/messages.admin-core.en.xlf
projects/admin-core/assets/locale/messages.admin-core.nl.xlf
projects/admin-core/src/lib/catalog/catalog-create-buttons/catalog-create-buttons.component.spec.ts
projects/admin-core/src/lib/catalog/geo-service-details/geo-service-details.component.spec.ts
projects/admin-core/src/lib/catalog/geo-service-form-dialog/geo-service-form-dialog.component.spec.ts
projects/admin-core/src/lib/catalog/geo-service-form/geo-service-form.component.css
projects/admin-core/src/lib/catalog/geo-service-form/geo-service-form.component.html
projects/admin-core/src/lib/catalog/geo-service-form/geo-service-form.component.spec.ts
projects/admin-core/src/lib/catalog/geo-service-form/geo-service-form.component.ts

[![HTM-1446](https://badgen.net/badge/JIRA/HTM-1446/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1446) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
[HTM-1446]: https://b3partners.atlassian.net/browse/HTM-1446?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

HTM-1446: Add configuration for WMS server type

---

package-lock.json
package.json
projects/core/src/lib/components/drawing/helpers/drawing.helper.ts

[![HTM-1458](https://badgen.net/badge/JIRA/HTM-1458/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1458) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
[HTM-1458]: https://b3partners.atlassian.net/browse/HTM-1458?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

HTM-1458: use UUID v4 to create FIDs instead of nanoid

---

projects/admin-api/src/lib/models/app-layer-settings.model.ts
projects/admin-core/src/lib/application/application-layer-settings/application-layer-settings.component.html
projects/admin-core/src/lib/application/application-layer-settings/application-layer-settings.component.ts
projects/api/src/lib/models/app-layer.model.ts
projects/api/src/lib/models/hidden-layer-functionality.model.ts
projects/api/src/lib/models/index.ts
projects/core/src/lib/components/attribute-list/attribute-list-export-button/attribute-list-export-button.component.spec.ts
projects/core/src/lib/components/attribute-list/attribute-list-export-button/attribute-list-export-button.component.ts
projects/core/src/lib/components/attribute-list/attribute-list/attribute-list.component.ts
projects/core/src/lib/components/attribute-list/services/attribute-list-manager.service.ts
projects/core/src/lib/components/feature-info/feature-info.service.ts

[![HTM-1435](https://badgen.net/badge/JIRA/HTM-1435/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1435) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
[HTM-1435]: https://b3partners.atlassian.net/browse/HTM-1435?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

HTM-1435: Add settings to hide some functionality for layers

---

projects/api/src/lib/models/extended-user-response.model.ts
projects/api/src/lib/services/tailormap-api-v1-mock.service.ts
projects/api/src/lib/services/tailormap-api-v1.service.model.ts
projects/api/src/lib/services/tailormap-api-v1.service.spec.ts
projects/api/src/lib/services/tailormap-api-v1.service.ts
projects/api/src/lib/services/tailormap-security-api-v1.service.model.ts
projects/api/src/lib/services/tailormap-security-api-v1.service.ts
projects/core/src/lib/services/user-login-check.service.ts

[![HTM-1470](https://badgen.net/badge/JIRA/HTM-1470/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1470) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
[HTM-1470]: https://b3partners.atlassian.net/browse/HTM-1470?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

HTM-1470: Only show user logged out message in case of unauthorized

---

projects/api/src/lib/models/extended-user-response.model.ts
projects/api/src/lib/services/tailormap-security-api-v1.service.ts
projects/core/src/lib/services/user-login-check.service.ts

[![HTM-1470](https://badgen.net/badge/JIRA/HTM-1470/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1470) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
[HTM-1470]: https://b3partners.atlassian.net/browse/HTM-1470?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

HTM-1470: Ignore (possibly temporary) Ajax errors

---

projects/map/src/lib/helpers/feature.helper.ts

[![EK-41](https://badgen.net/badge/JIRA/EK-41/pink?icon=jira)](https://b3partners.atlassian.net/browse/EK-41) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
to serialize ol.Geometry to GeoJson geometry
[EK-41]: https://b3partners.atlassian.net/browse/EK-41?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

EK-41: Add a toGeoJSON(olGeometry) function

---

projects/core/src/lib/components/drawing/create-drawing-button/create-drawing-button.component.html
projects/core/src/lib/components/drawing/create-drawing-button/create-drawing-button.component.spec.ts
projects/core/src/lib/components/drawing/create-drawing-button/create-drawing-button.component.ts
projects/core/src/lib/components/drawing/drawing/drawing.component.ts
projects/core/src/lib/components/drawing/state/drawing.actions.ts
projects/core/src/lib/components/drawing/state/drawing.reducer.ts
projects/core/src/lib/components/drawing/state/drawing.selectors.ts
projects/core/src/lib/components/filter/services/spatial-filter-crud.service.ts
projects/core/src/lib/components/filter/spatial-filter-form-draw-geometries/spatial-filter-form-draw-geometries.component.html
projects/core/src/lib/components/filter/spatial-filter-form-draw-geometries/spatial-filter-form-draw-geometries.component.ts
projects/core/src/lib/components/filter/spatial-filter-form/spatial-filter-form.component.html
projects/core/src/lib/components/filter/spatial-filter-form/spatial-filter-form.component.ts
projects/core/src/lib/map/components/map-drawing-buttons/map-drawing-buttons.component.html
projects/core/src/lib/map/components/map-drawing-buttons/map-drawing-buttons.component.spec.ts
projects/core/src/lib/map/components/map-drawing-buttons/map-drawing-buttons.component.ts
projects/map/src/lib/models/tool-manager.model.ts
projects/map/src/lib/models/tools/modify-tool.model.ts
projects/map/src/lib/openlayers-map/open-layers-tool-manager.ts
projects/map/src/lib/openlayers-map/tools/open-layers-modify-tool.ts

[![EK-7](https://badgen.net/badge/JIRA/EK-7/pink?icon=jira)](https://b3partners.atlassian.net/browse/EK-7) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
[EK-7]: https://b3partners.atlassian.net/browse/EK-7?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

EK-7: Enable modify tool for drawing features

---

projects/admin-core/src/lib/shared/components/admin-fields-renderer/admin-fields-renderer.component.css
projects/admin-core/src/lib/shared/components/admin-fields-renderer/admin-fields-renderer.component.html
projects/core/src/lib/components/drawing/state/drawing.actions.ts
projects/core/src/lib/components/drawing/state/drawing.reducer.ts

[![EK-39](https://badgen.net/badge/JIRA/EK-39/pink?icon=jira)](https://b3partners.atlassian.net/browse/EK-39) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
[EK-39]: https://b3partners.atlassian.net/browse/EK-39?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

EK-39: Fixes checkbox admin fields + added addFeatures action

---

projects/core/assets/locale/messages.core.de.xlf
projects/core/assets/locale/messages.core.en.xlf
projects/core/assets/locale/messages.core.nl.xlf
projects/core/src/lib/components/toolbar/clicked-coordinates/clicked-coordinates.component.css
projects/core/src/lib/components/toolbar/clicked-coordinates/clicked-coordinates.component.html
projects/core/src/lib/components/toolbar/clicked-coordinates/clicked-coordinates.component.spec.ts
projects/core/src/lib/components/toolbar/clicked-coordinates/clicked-coordinates.component.ts
projects/core/src/lib/layout/layout.service.ts

[![HTM-1468](https://badgen.net/badge/JIRA/HTM-1468/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1468) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
[HTM-1468]: https://b3partners.atlassian.net/browse/HTM-1468?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

HTM-1468: Refactor The Coordinate Picker Tool with navigation functionality

---

projects/map/src/lib/helpers/feature.helper.spec.ts
projects/map/src/lib/helpers/feature.helper.ts

[![EK-43](https://badgen.net/badge/JIRA/EK-43/pink?icon=jira)](https://b3partners.atlassian.net/browse/EK-43) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
[EK-43]: https://b3partners.atlassian.net/browse/EK-43?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

EK-43: Add support for circle geometries in the GeoJSON converter functions

---

projects/core/src/lib/components/toc/toc-node-details/layer-details/layer-details.component.html
projects/core/src/lib/components/toc/toc-node-details/layer-details/layer-details.component.ts
projects/core/src/lib/components/toc/toc-node-details/toc-node-details.component.html
projects/core/src/lib/components/toc/toc-node-details/toc-node-details.component.ts
projects/core/src/lib/components/toc/toc/toc.component.html
projects/core/src/lib/map/models/layer-tree-node-with-layer.model.ts
projects/core/src/lib/map/state/map.selectors.ts

[![HTM-1492](https://badgen.net/badge/JIRA/HTM-1492/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1492) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
[HTM-1492]: https://b3partners.atlassian.net/browse/HTM-1492?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

HTM-1492: Hide opacity slider in layer details in TOC for 3D Tiles

---

projects/core/src/lib/map/services/application-map.service.ts

[![HTM-1473](https://badgen.net/badge/JIRA/HTM-1473/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1473) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
[HTM-1473]: https://b3partners.atlassian.net/browse/HTM-1473?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

HTM-1473: Load Cesium.js on-demand instead of immediately

---

projects/map/src/lib/openlayers-map/cesium-map/cesium-manager.ts

[![HTM-1514](https://badgen.net/badge/JIRA/HTM-1514/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1514) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
[HTM-1514]: https://b3partners.atlassian.net/browse/HTM-1514?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

HTM-1514: Request render for 3D scene after 2D layers change

---

projects/map/src/lib/openlayers-map/cesium-map/cesium-manager.ts

- Remove unnecessary usage of async methods
- Use specific layer type inputs instead of returning null 
- Fix bug where layers where created multiple times when TOC was clicked very fast
- Add error handling to creating terrain layers

Refactor CesiumManager

---

projects/core/assets/locale/messages.core.de.xlf
projects/core/assets/locale/messages.core.en.xlf
projects/core/assets/locale/messages.core.nl.xlf
projects/core/src/lib/components/toc/toc-node-layer/toc-node-layer.component.css
projects/core/src/lib/components/toc/toc-node-layer/toc-node-layer.component.html
projects/core/src/lib/components/toc/toc-node-layer/toc-node-layer.component.ts
projects/shared/src/lib/components/split-button/split-button.component.css
projects/shared/src/lib/components/split-button/split-button.component.html

[![HTM-1496](https://badgen.net/badge/JIRA/HTM-1496/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1496) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
- not visible due to current zoom level: grey (same as now)
- not visible in 3D due to no web Mercator: strikethrough
- not visible in 2D (3D layers): grey with 3D icon next to it (with tooltip)
[HTM-1496]: https://b3partners.atlassian.net/browse/HTM-1496?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

HTM-1496: Show different reasons for layers not being visible differently

---

projects/core/src/lib/components/filter/services/filter-features.service.ts
projects/map/src/lib/helpers/map-style.helper.ts

[![HTM-1491](https://badgen.net/badge/JIRA/HTM-1491/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1491) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
this resolves the error shown in the ticket, but the buffer geometry is only drawn when you click on any of the other drawing buttons
[HTM-1491]: https://b3partners.atlassian.net/browse/HTM-1491?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

HTM-1491: Spatial filter: buffering circle does not work

---

projects/admin-core/src/lib/form/form-edit-field/form-edit-field.component.html

[![HTM-1549](https://badgen.net/badge/JIRA/HTM-1549/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1549) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
fix a regression caused by #878
[HTM-1549]: https://b3partners.atlassian.net/browse/HTM-1549?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

HTM-1549: restore option to disable any form field

---

projects/admin-core/src/lib/application/application-edit-filters/application-slider-filter-form/application-slider-filter-form.component.ts

[![HTM-1556](https://badgen.net/badge/JIRA/HTM-1556/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1556) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
Do not save 'initialLowerValue' and 'initialUpperValue' if the condition is not between, and do not save 'initialValue' if it is.
[HTM-1556]: https://b3partners.atlassian.net/browse/HTM-1556?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

HTM-1556: Do not save irrelevant values in slider config

---

projects/admin-core/src/lib/application/components/header-config/header-component-config.component.ts
projects/api/src/lib/helpers/base-component-config.helper.ts
projects/core/assets/icons/fullscreen.svg
projects/core/assets/icons/fullscreen_exit.svg
projects/core/assets/locale/messages.core.de.xlf
projects/core/assets/locale/messages.core.en.xlf
projects/core/assets/locale/messages.core.nl.xlf
projects/core/assets/tailormap-styles.css
projects/core/src/lib/components/header/header/header.component.css
projects/core/src/lib/components/header/header/header.component.ts
projects/core/src/lib/components/menubar/menubar.component.html
projects/core/src/lib/components/menubar/menubar.component.ts
projects/core/src/lib/layout/base-layout/base-layout.component.html
projects/core/src/lib/shared/components/bottom-panel/bottom-panel.component.css
projects/core/src/lib/shared/components/bottom-panel/bottom-panel.component.html
projects/core/src/lib/shared/components/bottom-panel/bottom-panel.component.spec.ts
projects/core/src/lib/shared/components/bottom-panel/bottom-panel.component.ts

[![HTM-1504](https://badgen.net/badge/JIRA/HTM-1504/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1504) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
Fixes:
HTM-1557: Header component disabled by default
HTM-1558: Hide application logo only if header logo is configured
HTM-1559: Fix overlap of header over maximized attribute list
[HTM-1504]: https://b3partners.atlassian.net/browse/HTM-1504?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

HTM-1504: Header component bugfixes

---

projects/core/src/lib/components/edit/edit/edit.component.html
projects/core/src/lib/components/edit/edit/edit.component.ts
projects/core/src/lib/components/edit/state/edit.reducer.ts

[![HTM-1519](https://badgen.net/badge/JIRA/HTM-1519/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1519) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
[HTM-1560]: https://b3partners.atlassian.net/browse/HTM-1560?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

HTM-1560: If there edit geometry type is point or line, don't show menu

---

projects/core/assets/locale/messages.core.de.xlf
projects/core/assets/locale/messages.core.en.xlf
projects/core/assets/locale/messages.core.nl.xlf
projects/core/src/lib/components/filter/filter-list-item/filter-list-item.component.html
projects/core/src/lib/components/toc/toc-node-layer/toc-node-layer.component.css
projects/core/src/lib/components/toc/toc-node-layer/toc-node-layer.component.html
projects/core/src/lib/components/toc/toc-node-layer/toc-node-layer.component.ts
projects/core/src/lib/components/toc/toc/toc.component.html
projects/core/src/lib/components/toc/toc/toc.component.spec.ts
projects/core/src/lib/components/toc/toc/toc.component.ts
projects/core/src/lib/filter/state/filter.selectors.ts

[![HTM-1535](https://badgen.net/badge/JIRA/HTM-1535/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1535) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
[HTM-1535]: https://b3partners.atlassian.net/browse/HTM-1535?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

HTM-1535: Show filter icon in toc for filtered layers

---

projects/admin-core/assets/locale/messages.admin-core.de.xlf
projects/admin-core/assets/locale/messages.admin-core.en.xlf
projects/admin-core/assets/locale/messages.admin-core.nl.xlf
projects/admin-core/src/lib/application/components/components.module.ts
projects/admin-core/src/lib/application/components/edit-config/edit-component-config.component.html
projects/admin-core/src/lib/application/components/edit-config/edit-component-config.component.ts
projects/api/src/lib/models/component-config/edit-config.model.ts
projects/api/src/lib/models/component-config/index.ts
projects/core/src/lib/components/edit/edit-dialog/edit-dialog.component.ts
projects/core/src/lib/components/edit/services/edit-feature.service.ts
projects/core/src/lib/services/feature-updated.service.ts

[![HTM-1573](https://badgen.net/badge/JIRA/HTM-1573/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1573) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)

HTM-1573: Add config option to close panel after adding new feature

---

projects/core/src/lib/map/services/drawing.service.ts
projects/core/src/lib/test-helpers/map-service.mock.spec.ts
projects/map/src/lib/models/tools/select-tool.model.ts
projects/map/src/lib/openlayers-map/tools/open-layers-select-tool.ts

[![HTM-1572](https://badgen.net/badge/JIRA/HTM-1572/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1572) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
[HTM-1572]: https://b3partners.atlassian.net/browse/HTM-1572?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

HTM-1572: Allow deselection of element that was just drawn

---

projects/core/src/lib/components/filter/filter-list/filter-list.component.ts

[![HTM-1584](https://badgen.net/badge/JIRA/HTM-1584/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1584) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)

HTM-1584: Show only filters for active layers

---

projects/admin-core/assets/locale/messages.admin-core.de.xlf
projects/admin-core/assets/locale/messages.admin-core.en.xlf
projects/admin-core/assets/locale/messages.admin-core.nl.xlf
projects/admin-core/src/lib/application/application-edit-filters/application-filterable-layers-list/application-filterable-layers-list.component.css
projects/admin-core/src/lib/application/application-edit-filters/application-filterable-layers-list/application-filterable-layers-list.component.html
projects/admin-core/src/lib/application/application-edit-filters/application-filterable-layers-list/application-filterable-layers-list.component.ts

[![HTM-1524](https://badgen.net/badge/JIRA/HTM-1524/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1524) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)

HTM-1524: List filter for filterable layers

---

projects/core/src/lib/components/edit/edit/edit.component.ts
projects/core/src/lib/components/edit/state/edit.actions.ts
projects/core/src/lib/components/edit/state/edit.state.ts

[![HTM-1587](https://badgen.net/badge/JIRA/HTM-1587/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1587) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
[HTM-1587]: https://b3partners.atlassian.net/browse/HTM-1587?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fixes HTM-1587: Unable to draw line when geometry type is linestring (instead of generic geometry)

---

projects/map/src/lib/helpers/ol-layer.helper.ts

[![HTM-1588](https://badgen.net/badge/JIRA/HTM-1588/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1588) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
[HTM-1588]: https://b3partners.atlassian.net/browse/HTM-1588?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fixes HTM-1588: Also use WMS POST request with untiled WMS when CQL_FILTER parameter is too large for a GET request

---

projects/admin-core/src/lib/catalog/geo-service-details/geo-service-details.component.spec.ts
projects/admin-core/src/lib/catalog/layer-settings-form/layer-settings-form.component.ts
projects/admin-core/src/lib/catalog/services/geo-service.service.ts
projects/map/src/lib/helpers/ol-layer.helper.ts

[![HTM-1591](https://badgen.net/badge/JIRA/HTM-1591/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1591) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
HTM-1591
[HTM-1591]: https://b3partners.atlassian.net/browse/HTM-1591?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

HTM-1591: Change default for tilingDisabled to true as in backend

---

projects/core/assets/locale/messages.core.de.xlf
projects/core/assets/locale/messages.core.en.xlf
projects/core/assets/locale/messages.core.nl.xlf
projects/core/src/lib/components/drawing/drawing/drawing.component.css
projects/core/src/lib/components/drawing/drawing/drawing.component.html
projects/core/src/lib/components/drawing/drawing/drawing.component.ts
projects/core/src/lib/components/drawing/helpers/drawing.helper.ts
projects/core/src/lib/components/drawing/models/drawing-feature.model.ts

[![EK-51](https://badgen.net/badge/JIRA/EK-51/pink?icon=jira)](https://b3partners.atlassian.net/browse/EK-51) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
[EK-51]: https://b3partners.atlassian.net/browse/EK-51?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

EK-51: Allow locked, non-editable, styles

---

projects/core/src/lib/components/drawing/drawing-style-form/drawing-style-form.component.ts
projects/core/src/lib/components/drawing/drawing-style-icon/drawing-style-icon.component.ts
projects/core/src/lib/components/drawing/helpers/drawing.helper.ts
projects/core/src/lib/components/drawing/models/drawing-feature.model.ts
projects/map/src/lib/helpers/map-style.helper.ts
projects/map/src/lib/helpers/style/arrow-style.helper.ts
projects/map/src/lib/helpers/style/label-style.helper.ts
projects/map/src/lib/helpers/style/stroke-style.helper.ts
projects/map/src/lib/models/map-style.model.ts
projects/shared/src/lib/helpers/style.helper.ts

[![EK-29](https://badgen.net/badge/JIRA/EK-29/pink?icon=jira)](https://b3partners.atlassian.net/browse/EK-29) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
[EK-29]: https://b3partners.atlassian.net/browse/EK-29?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

EK-29: Add additional line style properties

---

projects/admin-core/assets/locale/messages.admin-core.de.xlf
projects/admin-core/assets/locale/messages.admin-core.en.xlf
projects/admin-core/assets/locale/messages.admin-core.nl.xlf
projects/admin-core/src/lib/catalog/geo-service-form/geo-service-form.component.html
projects/admin-core/src/lib/catalog/geo-service-form/geo-service-form.component.ts
projects/admin-core/src/lib/shared/components/authorization-edit/authorization-edit.component.html
projects/admin-core/src/lib/shared/components/authorization-edit/authorization-edit.component.ts

See change in https://github.com/Tailormap/tailormap-api/pull/1312

Do not show the 'anyone' access chip for proxied secured services

---

.github/workflows/test-and-deploy.yml
README.md
ci/docker-compose.pr.yml
docker-compose.network.yml
docker-compose.traefik.yml
docker-compose.yml

[![HTM-1599](https://badgen.net/badge/JIRA/HTM-1599/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1599) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
requires https://github.com/Tailormap/tailormap-api/pull/1353
[HTM-1599]: https://b3partners.atlassian.net/browse/HTM-1599?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

HTM-1599: Update the production compose stack to include a configured prometheus service

---

projects/admin-core/src/lib/application/application-layer-tree/application-layer-tree.component.ts
projects/shared/src/lib/components/tree/helpers/drop-zone.helper.ts
projects/shared/src/lib/components/tree/tree-drag-drop.service.ts
projects/shared/src/lib/components/tree/tree.component.css
projects/shared/src/lib/components/tree/tree.component.html
projects/shared/src/lib/components/tree/tree.component.ts
projects/shared/src/lib/components/tree/tree.service.ts

[![HTM-1619](https://badgen.net/badge/JIRA/HTM-1619/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1619) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
[HTM-1619]: https://b3partners.atlassian.net/browse/HTM-1619?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

HTM-1619: Fixes disappearing layers from tree (toc, catalog)

---

projects/admin-core/src/lib/application/application-edit-filters/filters/application-checkbox-filter-form/application-checkbox-filter-form.component.ts

[![HTM-1628](https://badgen.net/badge/JIRA/HTM-1628/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1628) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
[HTM-1628]: https://b3partners.atlassian.net/browse/HTM-1628?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

HTM-1628: Change alias to undefined when the text is removed from the form field

---

projects/core/src/lib/components/edit/services/edit-map-tool.service.ts
projects/core/src/lib/components/edit/state/edit.actions.ts
projects/core/src/lib/components/edit/state/edit.effects.ts
projects/core/src/lib/components/feature-info/feature-info.service.ts
projects/core/src/lib/components/feature-info/feature-info/feature-info.component.ts
projects/map/src/lib/models/tools/map-click-tool.model.ts
projects/map/src/lib/openlayers-map/open-layers-tool-manager.spec.ts
projects/map/src/lib/openlayers-map/tools/open-layers-map-click-tool.spec.ts
projects/map/src/lib/openlayers-map/tools/open-layers-map-click-tool.ts

[![HTM-1609](https://badgen.net/badge/JIRA/HTM-1609/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1609) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
[HTM-1609]: https://b3partners.atlassian.net/browse/HTM-1609?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

HTM-1609: Increase margin for selecting objects with touch screen

---

projects/admin-core/src/lib/application/application-edit-filters/filters/application-checkbox-filter-form/application-checkbox-filter-form.component.ts

[![HTM-1634](https://badgen.net/badge/JIRA/HTM-1634/pink?icon=jira)](https://b3partners.atlassian.net/browse/HTM-1634) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
[HTM-1634]: https://b3partners.atlassian.net/browse/HTM-1634?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

HTM-1634: Do not emit a value when unique value input of checkbox filter is null

---

projects/admin-api/package.json
projects/admin-core/package.json
projects/api/package.json
projects/core/package.json
projects/core/src/lib/components/drawing/drawing/drawing.component.ts
projects/core/src/lib/map/services/drawing.service.ts
projects/map/package.json
projects/shared/package.json

[![EK-55](https://badgen.net/badge/JIRA/EK-55/pink?icon=jira)](https://b3partners.atlassian.net/browse/EK-55) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Tailormap&utm_campaign=badge_info)
[EK-55]: https://b3partners.atlassian.net/browse/EK-55?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

EK-55: Keep predefined style switching between polygon drawing tools
